### ISSUE TITLE
Detect which TabBarItem is Selected

### ISSUE THREAD

**Issue by sentiasa** [Ramotion/animated-tab-bar#107]
I have a question. Through `container.tag` (in RAMAnimatedTabBarController) we can access which Tab Bar Item is clicked. How can I get which item is clicked inside `playAnimation()` level? 

So I can use index number to apply different images for different tabBarItems

```
override public func playAnimation(icon : UIImageView, textLabel : UILabel) {
    var index = Get index of the TabBarItem pressed

    if index == 0 {
        // change img for left TabBarItem 
    } else if index == 5 {
      // change img for right TabBarItem
    }
}
```

I tried something like: `RAMAnimatedTabBarController.tabBar()` etc, but doesn't let me do that. 

Can you please help me? Thanks

**Comment by RajChanchal** [comment]
Any solution to above query yet??

**Comment by RajChanchal** [comment]
Well, I have found a workaround.
For that you need to subclass you `tabbarcontroller `to `RAMAnimatedTabBarController`
Then in the subclass ovveride the super class' method '`tapHandler`'

```
override func tapHandler(_ gesture: UIGestureRecognizer) {
        super.tapHandler(gesture)
        let currentIndex = gestureView.tag
    }
```

**Comment by furiosFast** [comment]
can you explain yourself better?
Thank's
