### ISSUE TITLE
setImageInsets tabBarItem

### ISSUE THREAD

**Issue by lsn-sokna** [Ramotion/animated-tab-bar#11]
I tried to change insets of every tabbaritems both programmatically and using storyboard. It doesn't work. 
![ios simulator screen shot feb 4 2015 2 42 07 pm](https://cloud.githubusercontent.com/assets/5226862/6036717/09151054-ac7c-11e4-84f9-a88692fdb97a.png)

Code that I tried:
    self.tabBarItem.imageInsets=UIEdgeInsetsMake(5, 0, -5, 0);
and also
    for (RAMAnimatedTabBarItem *item in self.tabBarController.tabBar.items) {
        item.imageInsets=UIEdgeInsetsMake(5, 0, -5, 0);
    }

Thanks!

**Comment by lsn-sokna** [comment]
I have fixed the problem by editing 
createConstraints(icon, container: container, size: item.image!.size, yOffset: -5)
=> createConstraints(icon, container: container, size: item.image!.size, yOffset: 2)
in RAMAnimatedTabBarController.swift:createCustomIcons.

Sorry for inconvenience!

Thanks!

**Comment by allenwong** [comment]
Are you set the tabBarItem directly in storyboard or programmably in UITabBarController? I have the same design requirement to remove the bar item title.

**Comment by Iccr** [comment]
> Are you set the tabBarItem directly in storyboard or programmably in UITabBarController? I have the same design requirement to remove the bar item title.

I changed"createConstraints" function   In RAMAnimatedTabBarController.swift file. It worked like a charm. Although I don't like it. If there is better solution please reply.
