### ISSUE TITLE
How can change color of each item bar?

### ISSUE THREAD

**Issue by mhtranbn** [Ramotion/animated-tab-bar#111]
When the first i go app, the bar item (text and icon) is White color.
How can change the color of each item bar?

**Comment by siegeout** [comment]
Have you changed the color?I have the same problem now.

**Comment by mhtranbn** [comment]
yup, i try change code to: 

`public func changColorItemBar( indexGray1: Int, indexGray2: Int, indexGray3: Int) {
        guard let items = tabBar.items as? [RAMAnimatedTabBarItem] else {
            fatalError("items error")
        }
        for item in items {
                let icon = item.iconView?.icon
            
                if (item == items[indexGray1] || item == items[indexGray2] || item == items[indexGray3]) && (indexGray2 != indexGray3) {
                    icon!.translatesAutoresizingMaskIntoConstraints = false
                    let container : UIImageView = item.iconView!.icon
                    container.tintColor = UIColor.grayColor()
                } else {
                    icon!.translatesAutoresizingMaskIntoConstraints = false
                    let container : UIImageView = item.iconView!.icon
                    container.tintColor = UIColor.whiteColor()
                }
        }
    }`

**Comment by mhtranbn** [comment]
And chang old code to:
            var icon = UIImageView()
//            if (item == items[indexGray1] || item == items[indexGray2] || item == items[indexGray3]) && indexGray1 != indexGray2 {
//                icon = UIImageView(image: item.image?.imageWithRenderingMode(.AlwaysTemplate))
//                
//            } else {
                icon = UIImageView(image: item.image?.imageWithRenderingMode(.AlwaysTemplate))
//            }

            icon.translatesAutoresizingMaskIntoConstraints = false

**Comment by siegeout** [comment]
Oh,yeah.Thanks for your answer,it helps me a lot.
