### ISSUE TITLE
Tap gesture container view size seems incorrect

### ISSUE THREAD

**Issue by foffux** [Ramotion/animated-tab-bar#118]
Hello
Here it is what I am experimenting:
tab bar tap gesture happens also if I click outside tab bar. This is not good at all.
Moreover, you do not have to tap directly on tab bar icon to to skip among tab bar item; you just need to tap in between of them. Also this behavior  is not good at all.
I thought it could be related, somehow, to:

``` javascript
viewContainer.addGestureRecognizer(tapGesture)
```

but I tried to investigate it without any luck.
Could you please help me with this?
Thank you.

**Comment by ober01** [comment]
All item frames are correct 
<img width="500" alt="image 2018-04-16 at 2 25 19 pm" src="https://user-images.githubusercontent.com/5435782/38806486-183f59a6-4182-11e8-8a6b-741180f5238b.png">
