### ISSUE TITLE
badgeValue for RAMAnimatedTabBarItem isn't rendered properly

### ISSUE THREAD

**Issue by ctews** [Ramotion/animated-tab-bar#12]
The screenshot explains the problem :)

![badgeValue misaligned](https://cloud.githubusercontent.com/assets/1607414/6203398/82714894-b520-11e4-849d-7db96f2bd683.png)

**Comment by codeSupreme** [comment]
Is there a fix to this problem because I am having the same issue.

**Comment by ober01** [comment]
fixed it in version 1.0.5
