### ISSUE TITLE
Change tabbar programatically

### ISSUE THREAD

**Issue by joaoh82** [Ramotion/animated-tab-bar#128]
I need to change the selected TabBar programatically and usually I would do it just like this.

`self.tabBarController?.selectedIndex = 2`

And it is working, but how do I do that and animate and change the selected tabbar icon to the correct one?

Thanks

**Comment by seven-ply** [comment]
+1

**Comment by kuyazee** [comment]
@seven-ply @joaoh82 you do this

     let animatedTabBar = self.tabBarController as! RAMAnimatedTabBarController
     animatedTabBar.setSelectIndex(from: self.tabBarController!.selectedIndex, to: 2)

**Comment by seven-ply** [comment]
@kuyazee you're awesome man. This works. Thank you very much.
