### ISSUE TITLE
Unable to Add badge after embedding a UINavigationController btween the View and RamTabBarController

### ISSUE THREAD

**Issue by aviralveddis** [Ramotion/animated-tab-bar#132]
The demo works fine but as soon as you embed a Navigation controller, badge does not work.

**Comment by rickyjwhong** [comment]
+ 1

**Comment by rickyjwhong** [comment]
Just re ran this, and there is a work around. Just set the badge icon/number after the view has been loaded (view did load of the view controller you want this to be on).
