### ISSUE TITLE
Push v2.0.1 to CocoaPods Specs repo

### ISSUE THREAD

**Issue by LouisDhauwe** [Ramotion/animated-tab-bar#138]
Correct me if I'm wrong, but it seems the latest versions (v2.0.0 and v2.0.1) have not been pushed to the CocoaPods Specs repo. 

[The pod page](http://cocoapods.org/pods/RAMAnimatedTabBarController) shows v1.5.3, as does the [readme of this repo](https://github.com/Ramotion/animated-tab-bar/blob/master/README.md).

**Comment by Jucedik** [comment]
+1
