### ISSUE TITLE
Delegate methods not being called

### ISSUE THREAD

**Issue by matthewpalmer** [Ramotion/animated-tab-bar#14]
I have a subclass of RAMAnimatedTabBarController that works fine except that `func tabBarController(tabBarController: UITabBarController, didSelectViewController viewController: UIViewController)` is never called.

If my class is 

```swift
class MasterTabBarViewController: RAMAnimatedTabBarController, UITabBarControllerDelegate
```

then that delegate method is never called.

But if I change it to

```swift
class MasterTabBarViewController: UITabBarController, UITabBarControllerDelegate
```

then it works as expected.

How can I get RAMAnimatedTabBarController to pass along the delegate method calls?

**Comment by matthewpalmer** [comment]
I'm happy to implement a fix and submit a PR, I just need to be pointed in the right direction, know what stuff to read up on, etc.

Thanks!

**Comment by ctews** [comment]
Is the delegate method implemented in the RAMAnimatedTabBarController and is calling [super ...]?

So honestly I don't know if this repo really gets reviewed by its owners, hope so but there are never any answers to issues from them as far as I can see :(

**Comment by matthewpalmer** [comment]
Thanks for your help! I think I have been able to get it working. I won't submit a PR but I'll leave a couple of quick notes for anyone in the future.

At the end of `the `tapHandler` function in RAMAnimatedTabBarController, add `self.tabBar(tabBar, didSelectItem: items[currentIndex])`.

Then add the function 

    override func tabBar(tabBar: UITabBar, didSelectItem item: UITabBarItem!) {
        super.tabBar(tabBar, didSelectItem: item)
    }

to that file. Calling super.tabBar... straight from `tapHandler` didn't seem to work.

`super` **must** implement tabBar:didSelectItem: otherwise you will get a crash at runtime. I tried to do a super.respondsToSelector("tabBar:didSelectItem:") check but I couldn't get that working either. If you need to know more about your super object you can call `println(super.description)` from within that method.

**Comment by andr-ggn** [comment]
any solutions?

**Comment by yuriferretti** [comment]
I just made a PR for UITabBarControllerDelegate protocol calls the problemas was that the UITabBarController subclass was not calling the delegate methods

```swift

func tapHandler(gesture:UIGestureRecognizer) {

        let items = tabBar.items as! [RAMAnimatedTabBarItem]
        
        let currentIndex = gesture.view!.tag
        let viewController = viewControllers![currentIndex] as! UIViewController
        
        if let shouldSelect = delegate?.tabBarController?(self, shouldSelectViewController: viewController)
            where !shouldSelect
        {
            return
        }

        if selectedIndex != currentIndex {
            var animationItem : RAMAnimatedTabBarItem = items[currentIndex]
            var icon = iconsView[currentIndex].icon
            var textLabel = iconsView[currentIndex].textLabel
            animationItem.playAnimation(icon, textLabel: textLabel)

            let deselelectIcon = iconsView[selectedIndex].icon
            let deselelectTextLabel = iconsView[selectedIndex].textLabel
            let deselectItem = items[selectedIndex]
            deselectItem.deselectAnimation(deselelectIcon, textLabel: deselelectTextLabel)
            selectedIndex = gesture.view!.tag
            delegate?.tabBarController?(self, didSelectViewController: viewController)
        }
    }

```

**Comment by ober01** [comment]
thanks yuriferretti, I added call delegate methods
