### ISSUE TITLE
hidesBottomBarWhenPushed and animationTabBarHidden

### ISSUE THREAD

**Issue by dorinsimina** [Ramotion/animated-tab-bar#144]
I'm trying to use the library in order to navigate from a tabbed bar screen to a full screen view controller. By using  hidesBottomBarWhenPushed in conjunction with animationTabBarHidden I've noticed a strange behavior: when coming back the icon images disappears.

Does anyone experienced this issue?

**Comment by allenwong** [comment]
I have same issue, sigh.

**Comment by Mosaics** [comment]
I have same issue too.

**Comment by akashlazy** [comment]
I have same issue too hidesBottomBarWhenPushed not work icons still appearing

**Comment by BaluNaik** [comment]
I have same issue

**Comment by ober01** [comment]
HidesBottomBarWhenPushed is hard to implement. But you could hide `AnimationTabBar` manually. Use this method https://is.gd/g1k8PQ

**Comment by Sabellus** [comment]
uncheck translucent property in tabbar
