### ISSUE TITLE
How can i use when i don't use storyBoard,i just use only code

### ISSUE THREAD

**Issue by lucy12356** [Ramotion/animated-tab-bar#148]
i don't know how to set tabBarItem to RAMAnimatedTabBarItem by code.can you provide a project by only code. sorry i'm a novice

**Comment by XiaoChenYung** [comment]
let tabBarIconHome: RAMAnimatedTabBarItem = RAMAnimatedTabBarItem(title: "Title1", image: #imageLiteral(resourceName: "image").withRenderingMode(.alwaysOriginal), selectedImage: #imageLiteral(resourceName: "image"))
        tabBarIconHome.animation = RAMBounceAnimation()
    
let tabBarIconProfile: RAMAnimatedTabBarItem = RAMAnimatedTabBarItem(title: "title", image: #imageLiteral(resourceName: "image").withRenderingMode(.alwaysOriginal), selectedImage: #imageLiteral(resourceName: "image").withRenderingMode(.alwaysOriginal))
        tabBarIconProfile.animation = RAMBounceAnimation()

let homeNavController = UINavigationController(rootViewController: HomeVC())
    homeNavController.tabBarItem = tabBarIconHome

let profileNavController = UINavigationController(rootViewController: ProfileVC())
    profileNavController.tabBarItem = tabBarIconProfile

let tabController = RAMAnimatedTabBarController(viewControllers: [homeNavController, profileNavController])

window?.rootViewController = tabController
window?.makeKeyVisible()
