### ISSUE TITLE
How can i set the plus button?

### ISSUE THREAD

**Issue by CrazyDavis** [Ramotion/animated-tab-bar#149]
like the Roles in the main page About

**Comment by Mohamed3amer** [comment]
@CrazyDavis did you know how to make it ?

**Comment by Mohamed3amer** [comment]
You can make it by

1. setting yOffSet property in the RAMAnimatedTabBarItem instance

**Comment by Mohamed3amer** [comment]
You can make it by
1. setting the yOffSet in the RAMAnimatedTabBarItem
2. use bigger image icon than the other tabs
