### ISSUE TITLE
Building an app using this tab bar without storyboard is a nightmare

### ISSUE THREAD

**Issue by iwheelbuy** [Ramotion/animated-tab-bar#150]
```
class MainView: RAMAnimatedTabBarController {
    
    convenience init() {
        let controllerEvents = UINavigationController(rootViewController: EventsView())
        controllerEvents.tabBarItem = EventsViewTabItem()
        let controllerPhotos = UINavigationController(rootViewController: PhotosView())
        controllerPhotos.tabBarItem = EventsViewTabItem()
        let viewControllers = [
            controllerEvents,
            controllerPhotos
        ]
        self.init(viewControllers: viewControllers)
    }
}

class EventsViewTabItem: RAMAnimatedTabBarItem {
    
    override init() {
        super.init()
        image = UIImage(named: "event.png")
        title = "Events"
        animation = RAMBounceAnimation()
    }
}
```

`iconView` is `nil`. why not checking it before unwrapping...

![2016-11-15 17 12 42](https://cloud.githubusercontent.com/assets/2524584/20301682/df73778c-ab56-11e6-9dcd-22ea0a7f63fa.png)

**Comment by JustinM1** [comment]
For most use cases you don't need to subclass. I got it working in code by doing it this way.

    let tabBarIconHome: RAMAnimatedTabBarItem = RAMAnimatedTabBarItem(title: "Title1", image: #imageLiteral(resourceName: "image").withRenderingMode(.alwaysOriginal), selectedImage: #imageLiteral(resourceName: "image"))
            tabBarIconHome.animation = RAMBounceAnimation()
        
    let tabBarIconProfile: RAMAnimatedTabBarItem = RAMAnimatedTabBarItem(title: "title", image: #imageLiteral(resourceName: "image").withRenderingMode(.alwaysOriginal), selectedImage: #imageLiteral(resourceName: "image").withRenderingMode(.alwaysOriginal))
            tabBarIconProfile.animation = RAMBounceAnimation()

    let homeNavController = UINavigationController(rootViewController: HomeVC())
        homeNavController.tabBarItem = tabBarIconHome
    
    let profileNavController = UINavigationController(rootViewController: ProfileVC())
        profileNavController.tabBarItem = tabBarIconProfile
    
    let tabController = RAMAnimatedTabBarController(viewControllers: [homeNavController, profileNavController])

    window?.rootViewController = tabController
    window?.makeKeyVisible()

**Comment by ober01** [comment]
This project prefer using storyboard
