### ISSUE TITLE
Tabbar Controller Not Hidden

### ISSUE THREAD

**Issue by JDModi** [Ramotion/animated-tab-bar#153]
How To hide Animated Tabbar ?

**Comment by JDModi** [comment]
Okay Its Solve....  

 override func viewWillAppear(_ animated: Bool) {
        let animatedTabBar = self.tabBarController as! RAMAnimatedTabBarController
        animatedTabBar.animationTabBarHidden(true)
    }
    override func viewWillDisappear(_ animated: Bool) {
        let animatedTabBar = self.tabBarController as! RAMAnimatedTabBarController
        animatedTabBar.animationTabBarHidden(false)
    }

**Comment by RodrigoGafa** [comment]
Thanks, awesome contribution!

**Comment by AliAyasrah** [comment]
thanks man

**Comment by OhKanghoon** [comment]
thx man~

**Comment by furiosFast** [comment]
same problem in iOS 12
