### ISSUE TITLE
fatalError("add items in tabBar")

### ISSUE THREAD

**Issue by EvilNOP** [Ramotion/animated-tab-bar#154]
I've setup everything in storyboard(follow the usage, one tab bar controller and two view controllers), it's weird that I got the fatalError("add items in tabBar")!

**Comment by spaluchiewicz** [comment]
I went through usage guide and I've got the same result 

`fatal error: add items in tabBar: file /Users/[...]/Pods/RAMAnimatedTabBarController/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift, line 371`

I updated RAMAnimatedTabBarController pod to newest version in my Podfile:

`pod 'RAMAnimatedTabBarController' `

```
$ pod --version
1.1.1
```

**Comment by AnChiChang** [comment]
I think maybe when you setup your custom image in storyboard, you choice wrong place. Not setup in Tab Bar Item Selected Image. you have to setup in Bar Item Image. Please check.

**Comment by denizoztreves** [comment]
You need to link the animation object with the tabBar item in order to get rid of the problem.

On storyboard editor right click to tab bar item and a black screen will appear ( the one shows delegates and stuff) then reference your animation accordingly. This error should dissappear

**Comment by prbehera8** [comment]
I did the same things and my tabBar item looks good but getting fatal error.

**Comment by DogTwoChen** [comment]
set your viewcontrollers class
