### ISSUE TITLE
shadow above tab bar in IOS 9.2

### ISSUE THREAD

**Issue by yujia917** [Ramotion/animated-tab-bar#157]
The tab bar works fine when testing in IOS 8.1. But there is a shadow above it when testing in IOS 9.2.

I make it red color. The red color is actually the background color of the view controller. And there is a table view in the view controller. Please see screen shots below. How could I solve it?

Thanks in advance.

In IOS 8.1:

![screen shot 2016-12-21 at 11 37 26 pm](https://cloud.githubusercontent.com/assets/12704261/21415356/f0f91d76-c7d6-11e6-82ab-16e2463615b8.png)

In IOS 9.2:

![screen shot 2016-12-21 at 11 37 48 pm](https://cloud.githubusercontent.com/assets/12704261/21415361/fe28052a-c7d6-11e6-910d-0f18fe3bfed3.png)

**Comment by ober01** [comment]
in last version it's fixed
