### ISSUE TITLE
Can't install with swift 3

### ISSUE THREAD

**Issue by shjnbe** [Ramotion/animated-tab-bar#158]
I  can't install with swift 3
I using xcode 8.2
Help me please

<img width="615" alt="untitled" src="https://cloud.githubusercontent.com/assets/12808073/21452183/b50483b6-c937-11e6-9584-3857fa494123.png">

**Comment by niunaruto** [comment]
mee to

**Comment by RodrigoGafa** [comment]
Have you solve your issue?, I have succesfully installed on swift 3.

**Comment by niunaruto** [comment]
you need platform :ios, '9.0'

**Comment by thecorsair** [comment]
pod repo update
