### ISSUE TITLE
 fatalError("add image icon in UITabBarItem") but image aleary added

### ISSUE THREAD

**Issue by Astoration** [Ramotion/animated-tab-bar#163]
```swift
guard let itemImage = item.image else {
        fatalError("add image icon in UITabBarItem")
      }
```
Exception from this line
```xml
<tabBarItem
    key="tabBarItem"
    title=""
    image="footer_icon_02_00"
    selectedImage="footer_icon_02_00"
    id="LJR-hK-R4Q"
    customClass="RAMAnimatedTabBarItem"
    customModule="RAMAnimatedTabBarController">
```
However, every item on the storyboard has an image added
What is the problem?
```swift
super.viewDidLoad()
        let items = tabBar.items
        for item in items!{
            let image = item.image!
        }
```
In addition, I've tested this code and I've definitely added an image

version information : 'RAMAnimatedTabBarController', '~> 2.0.13' / swift3

**Comment by zemtsov-artem** [comment]
I have this problem too

**Comment by prakashRavi1990** [comment]
Have you got solution for this???

**Comment by Astoration** [comment]
Deleting the exception line will work normally.
However, when the animation is not playing, the icon is not visible.
In this case, the animation will be resolved by stopping the frame at the 0th index.

**Comment by macro-dadt** [comment]
make sure that you set custom image for Bar Item (not Tab Bar Item)
