### ISSUE TITLE
Tabbar with larger middle button as shown in screenshot

### ISSUE THREAD

**Issue by ThreadPitt** [Ramotion/animated-tab-bar#165]
Hi,

the design example on the page looks great, what would be the approach to create a larger middle tab bar item (e.g. "Roles" in the image) with the animated tab bar?

Thx & Cheers
Thread

**Comment by RayanSaeed** [comment]
+1

**Comment by BeGooD33** [comment]
+1

**Comment by al-babar** [comment]
If anybody finds solution for it?

**Comment by RayanSaeed** [comment]
Actually it's very simple.
I did it like this

If I had 5 tabs, all of my other 4 tab's images were 50x50 ... So I made the middle one 50x85 and used Photoshop to make sure it looks just the way I want it to be.

**Comment by AimenS** [comment]
It's not possible to override RAMAnimatedTabBarController. I saw it's an imageView, so we can round the middle item, but I can't override this class.

**Comment by ErAshu** [comment]
Any update on this??

**Comment by priyonto** [comment]
Any update on this?

**Comment by ober01** [comment]
You could use `yOffset` to move items look for https://is.gd/jK1uRA
