### ISSUE TITLE
Animation stuck when change initial selected item index to 1 ? 

### ISSUE THREAD

**Issue by fadylateef** [Ramotion/animated-tab-bar#166]
I'd like middle tabbar item to be the initial view controller , so in AppDelegate.swift 

```
        let ram = self.window?.rootViewController as! RAMAnimatedTabBarController
        ram.setSelectIndex(from: 0, to: 1)
```

It selects the second item successfully , but the first item animation is stuck as the image below.

<img width="426" alt="screen shot 2017-03-19 at 2 17 11 pm" src="https://cloud.githubusercontent.com/assets/17549441/24080358/3b5a0740-0ca6-11e7-8d52-0be1cb93dd0a.png">

any help ?! 

Thanks in advance for great library 👍

**Comment by ober01** [comment]
in the current version work!
<img width="1419" alt="work" src="https://user-images.githubusercontent.com/5435782/38976238-60a1a9ea-43b9-11e8-86c7-bbfa6d44f25e.png">
