### ISSUE TITLE
Selected Tab Bar on load

### ISSUE THREAD

**Issue by jpsanabria** [Ramotion/animated-tab-bar#172]
I have 3 tab bar items. i would like the center tab bar item to be active on the initial load. Usually this is accomplished in ViewDidLoad of the TabBarController but I do not want to edit your code. Is their another way to accomplish this?

**Comment by dipkasyap** [comment]
Same here, any workaround is made ? Please do update on this issue.

**Comment by SamuraiJack76** [comment]
Would like to have that, too!

**Comment by ober01** [comment]
For changing active tab you can use this method https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L173
