### ISSUE TITLE
Remove TabBarItem [Enhancement]

### ISSUE THREAD

**Issue by ugenlik** [Ramotion/animated-tab-bar#173]
Is it possible to add an extension function to remove one of the tabbars? 

I try 

`self.viewcontrollers?.remove(at:index)`

this accomplishes to remove the tabbaritem at index.  but iconviews frames stays in the initial position, it doesn't update the frame/container of the tabbar items.

when clicking bars you can understand it removed the tabbaritem but on the display all baritems are visible and in the initial position

**Comment by ikolpachkov** [comment]
Now you can setup new `viewControllers` array, animated tab bar will recreate it self
