### ISSUE TITLE
Can't use titlePositionAdjustment

### ISSUE THREAD

**Issue by yMiecie** [Ramotion/animated-tab-bar#178]
Hello,

I would like to move down titles in `RAMAnimatedTabBarItem` but `titlePositionAdjustment` does nothing.

I tried to modify the `iconView?.textLabel` frame and layer but it also does nothing.

Is there any way to modify the title position ?
If not, is it possible to make `titlePositionAdjustment` work ?

Best Regards,
Yann

**Comment by furiosFast** [comment]
modify the value of yOffset in this line of code:
`createConstraints(textLabel, container: container, width: textLabelWidth, yOffset: 18 - item.yOffSet, heightRelation: .greaterThanOrEqual)`
in RAMAnimatedTabBarController
