### ISSUE TITLE
Not working tintColor 

### ISSUE THREAD

**Issue by testfooyy** [Ramotion/animated-tab-bar#184]
The color of the image does not change.
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        UITabBar.appearance().tintColor = UIColor.red
        return true
    }

**Comment by ober01** [comment]
Yes, UITabBar.appearance().tintColor not supported. Instead, you can use  https://goo.gl/hV5sBY for changing color

**Comment by veer9002** [comment]
How to change selected item text and icon color. I am getting the default blue color as selected color even after changing image tint color.
