### ISSUE TITLE
Is RTL Languages supported?

### ISSUE THREAD

**Issue by mn288** [Ramotion/animated-tab-bar#186]
tabbar not switching  on RTL Languages

**Comment by Abdul-Hannan** [comment]
no

**Comment by mn288** [comment]
This should be added soon..

**Comment by mn288** [comment]
I created a [PR](https://github.com/Ramotion/animated-tab-bar/pull/228/commits/0c2a124d4f05fd067c35e059d4ad0fab4d7de468) to solve this issue
