### ISSUE TITLE
Two Tabs selected at the same time

### ISSUE THREAD

**Issue by ignasibm** [Ramotion/animated-tab-bar#187]
Hey guys, I run into this issue a couple of times now: Sometimes when the previous tab stays selected after you select a new one, and you end up with 2 highlighted sections instead of just one.

Here's an screenshot:

![tabbar](https://user-images.githubusercontent.com/17671368/29748557-459039ae-8b19-11e7-8f69-b67200106626.png)

I haven't been able to replicate it consistently but several people have reported this bug. Any idea of what could be causing this?

More info: I'm using RAMAnimatedTabBarController swift implementation on my Obj-C project

**Comment by Zeynal7** [comment]
I am facing the same issue. If I switch between the tabs quickly, then it doesn't deselect the old tab.

**Comment by Zeynal7** [comment]
For anybody facing the same issue:

I realized that the reason was Hero animation library. This and Hero animation were having some kind of conflict when used together. You can fix it by disabling tab bar when hero animation (or any animation) is in progress.


```
viewDidLoad() {
...
        Hero.shared.delegate = self
}

extension TabBarController: HeroTransitionDelegate {
    func heroTransition(_ hero: HeroTransition, didUpdate state: HeroTransitionState) {
        if state == .starting {
            tabBar.isUserInteractionEnabled = false
        } else if state == .completing {
            tabBar.isUserInteractionEnabled = true
        }
    }

    func heroTransition(_ hero: HeroTransition, didUpdate progress: Double) { }
}

```
