### ISSUE TITLE
DO NOT USE THIS FUCKING SHIT

### ISSUE THREAD

**Issue by haiyo** [Ramotion/animated-tab-bar#188]
It will mess up your project! If you insist on trying, backup first!

**Comment by andreyoshev** [comment]
Why?

**Comment by Jauzee** [comment]
@haiyo use Git and your project will be in safe. And don't use foul lang, there is no `reset` for your reputation.

If you have any issues, report them as the people do; if you can do better (there is always room for improvement), make an PR.
