### ISSUE TITLE
How can I  use it with storyboard references ?

### ISSUE THREAD

**Issue by chenshipeng** [Ramotion/animated-tab-bar#189]

**Comment by SwiftRabbit** [comment]
The same way you would use a normal UITabBarViewController, but just make a subclass and use it in your storyboard?

**Comment by LordOfTheRains** [comment]
I use the storyboard references and I always get the "fatalError("items must inherit RAMAnimatedTabBarItem")"  error. I've tried adding the tab bar in the child view controllers storyboard, following the steps for bar items. also tried just setting them in the storyboard where I have the tab bar controller. none of it works.  only work when i have the view controller in the same board.

**Comment by ikolpachkov** [comment]
Please take a look at `RAMAnimatedTabBarDemo`
