### ISSUE TITLE
If the display on the iPhone X will appear at the bottom

### ISSUE THREAD

**Issue by Xingefb** [Ramotion/animated-tab-bar#194]
<img width="384" alt="screen shot 2017-09-27 at 4 30 49 pm" src="https://user-images.githubusercontent.com/15796453/30903417-51be74a6-a334-11e7-88a4-686056642c34.png">

How do i modify it on the iPhone X.

**Comment by berenyiaustin** [comment]
How did you solve this problem @Xingefb ?

**Comment by Xingefb** [comment]
Which version ？

**Comment by magneticrob** [comment]
@berenyiaustin this fixed it for me: https://github.com/Ramotion/animated-tab-bar/commit/4a8d57887cf4ffc9e8ced69627e21733e9d658d3

**Comment by AmeerTgh** [comment]
how to handle in landscape mode?
