### ISSUE TITLE
Items are too far down if app is launched horizontally

### ISSUE THREAD

**Issue by wozniakpl** [Ramotion/animated-tab-bar#195]
I'm setting up the TabBar correctly, everything works and looks fine when I'm starting the app in portrait orientation. Although, if I start it holding iPhone horizontally and then turning it to portrait, icons somehow are too far down and I can see ~60% of them.

What can cause this or how can I avoid it?

**Comment by alouanemed** [comment]
Same issue, were you able to solve this?
