### ISSUE TITLE
fatalError("items must inherit RAMAnimatedTabBarItem")

### ISSUE THREAD

**Issue by YouSour** [Ramotion/animated-tab-bar#196]
hi , i spend 2 hours now , check this problem , i'm using this library by cocoa pod , i do like what usage step 1 to 5 complete , i get error  fatalError("items must inherit RAMAnimatedTabBarItem") when run , i notice that on ur example project when set the class of the UITabBarController to RAMAnimatedTabBarController "module" can empty but on my project can't that problem , pls fix it , thank you for advance

**Comment by ikolpachkov** [comment]
Please check every tab bar item they all should be inherited from RAMAnimatedTabBarItem.

**Comment by lyc2345** [comment]
As I set UITabBarItem Class as RAMAniamatedTabBarItem in storyboard reference after I set storyboard reference as viewControllers of tabbar.

When ViewDidLoad I set a breakpoint and check my item is really RAMAnimatedTabBarItem but as long as I tap to trigger tapHandler This first optional check 
`guard let items = tabBar.itmes as? [RAMAnimatedTabBarItem] ` always fails
