### ISSUE TITLE
NSUnknownKeyException', reason: '[<UITabBarItem 0x7ff41c40b3b0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key animation.

### ISSUE THREAD

**Issue by satyam04** [Ramotion/animated-tab-bar#197]
I followed all the 5 steps carefully but I don't know why this error is coming.
I tried to search for the solution in stackoverflow and some other websites, but it was not helpful.
Please help

**Comment by Akamajin** [comment]
Did you solve the problem?

**Comment by Karanjks** [comment]
Hellow Please let know how to fix it...

**Comment by PrakashMaharjan** [comment]
Getting same error ..

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITabBarItem 0x102e02f50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key animation.'

Does anybody solved this issue? Is it bug?

**Comment by BaluNaik** [comment]
@satyam04 @Akamajin Hey try this [NMAnimatedTabBarItem](https://cocoapods.org/pods/NMAnimatedTabBarItem)

**Comment by 0ber** [comment]
if you have this issue `this class is not key value coding-compliant for the key animation` you have a problem with `key codding` in storyboard
