### ISSUE TITLE
Cannot find icon images on specified path

### ISSUE THREAD

**Issue by jlnbuiles** [Ramotion/animated-tab-bar#198]
I followed your readme to configure my project and I added images to each of my tab bar items in IB. 

However I'm unable to get the library to find my images. It crashes on `RAMFrameItemAnimation` ln. 46. 

This log entry should be a little more descriptive because all it prints out is `fatal error: <file where the crash occurs>`.

After doing a little bit of research I found that it is creating a path with a plist I added to configure a google analytics library: `<my path>/Application/9134A549-8DA6-4CB5-8CC9-2573F4554385/<my app name>.app/GoogleService-Info.plist`. This is because there is no value in a variable called `imagesPath` so it calls `Bundle.main.path(forResource: imagesPath, ofType:"plist")` which returns that.

How can I know in what my plist my images are? is this a bug on your end or is it apple for returning this other plist?

**Comment by darshan2509** [comment]
Same issue here. Did you manage to fix it? @jlnbuiles
