### ISSUE TITLE
Center tab bar item

### ISSUE THREAD

**Issue by atalayasa** [Ramotion/animated-tab-bar#204]
Hello, I have 5 tab bar items and when user pressed center button first time it will go that view controller but I need also when user clicked same button second time it needs to close that center view controller and go back to main one. Also when user pressed first time its image should be changed to close icon but I can not figure it out how can I achieve this. Can you please help me?

**Comment by kieuquangloc147** [comment]
I have the same problem too, could you help @RamotionRussell ?

**Comment by kieuquangloc147** [comment]
@atalayasa you can use this method https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L173

**Comment by atalayasa** [comment]
@kieuquangloc147 Thanks for answer but did you solve when user pressed center button second time it needs to go first screen again?

**Comment by kieuquangloc147** [comment]
You can check that event in UITabbarControllerDelegate, if tab index selected
yourNav?.setViewControllers([firstVC], animated: false)

**Comment by atalayasa** [comment]
@kieuquangloc147 I'll try and comment thank you so much.

**Comment by atalayasa** [comment]
I have tried but it did not work think I am doing something wrong. In my case there is a table view on 3rd view controller when user select something from that table view it should have navigate to first screen. How can I achieve it? Thanks

**Comment by kieuquangloc147** [comment]
Hi @atalayasa 

for changing selected index from the first to the third, I used
```
_rootTabBar?.selectedViewController = _homeNav (_homeNav is my third tab)
_rootTabBar?.setSelectIndex(from: 0, to: 2) (My tabbar has 5 tabs, I want to select the third tab default)
```

for changing images
![change image and color](https://user-images.githubusercontent.com/8148640/34527643-c3d45942-f0d8-11e7-9248-c1fcc98f451d.gif)

**Comment by atalayasa** [comment]
Thanks to your detailed answer but I need to change icon completely not its color how can I do it?
