### ISSUE TITLE
tintColor of selected item

### ISSUE THREAD

**Issue by veer9002** [Ramotion/animated-tab-bar#206]
First a fall, I want to say thank you very much for creating such a beautiful library. I love your lib, but I want to change the selectedItemImageColor and it's text color. I am able to change the tabbar item's text and icon color but not find any solution to change the default blue color for selectedItem. I want to change the color of selectedItemText and icon color. I tried Image tint from tab bar (storyboard) but still not changing the selectedItem color. When I change the class of tabbar controller to its default class (UITabbarController). It allow me to change the the selected item color.

Thanks.

**Comment by PiotrPawlus** [comment]
up

**Comment by furkankadioglu** [comment]
up!

**Comment by ober01** [comment]
You can change tint color in RAMItemAnimation https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMItemAnimationProtocol.swift#L52-L59 

![tint-color](https://user-images.githubusercontent.com/5435782/35622603-773a72f2-0699-11e8-810d-8e3d3866dcec.png)

**Comment by aserdah** [comment]
thank @ober01 ober01  for your answer

**Comment by Angelzzz** [comment]
Anyone can you help me to set unselected item color for RAMAnimatedTabBarController

**Comment by amit2908** [comment]
I am not able to change even the unselected item color to default color.

**Comment by marcelosalloum** [comment]
I've created the following convenience init method, I hope it helps you guys

```
extension RAMAnimatedTabBarItem {
    convenience init(title: String, image: UIImage?, tag: Int, animation: RAMItemAnimation, selectedColor: UIColor, unselectedColor: UIColor) {
        self.init(title: title, image: image, tag: 0)
        animation.iconSelectedColor = selectedColor
        animation.textSelectedColor = selectedColor
        self.animation = animation
        self.textColor = unselectedColor
        self.iconColor = unselectedColor
    }
}
```

**Comment by ShenYj** [comment]
it's worked!
