### ISSUE TITLE
when setting the tabBarController ,there is a promblem

### ISSUE THREAD

**Issue by qigeligedongdongqiang** [Ramotion/animated-tab-bar#207]
![image](https://user-images.githubusercontent.com/18454084/35315443-68aaca30-0107-11e8-9115-e26ef28951f0.png)
![image](https://user-images.githubusercontent.com/18454084/35315550-f04d8eb4-0107-11e8-8e3e-6a666dd7dea9.png)

when I set the tabBarController like this, it will crash at the following line
![image](https://user-images.githubusercontent.com/18454084/35315478-891760ee-0107-11e8-8ed3-c888c6dc141e.png)

**Comment by 0ber** [comment]
you need inherit each item from RAMAnimatedTabBarItem look example https://github.com/0ber/AnimatedTabBar-Pod-Test
