### ISSUE TITLE
this class is not key value coding-compliant for the key animation

### ISSUE THREAD

**Issue by Karanjks** [Ramotion/animated-tab-bar#208]
Please let me know how to fix this error.

**Comment by PrakashMaharjan** [comment]
Getting same error ..

*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITabBarItem 0x102e02f50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key animation.'

Does anybody solved this issue? Is it bug?

**Comment by ober01** [comment]
<img width="981" alt="keyvalue" src="https://user-images.githubusercontent.com/5435782/35630090-75b80e72-06b1-11e8-9c7e-40e5032f4204.png">

**Comment by Karanjks** [comment]
Dear,

 I already did it but still same issue.

Regards,
Karan Mehta.

**Comment by Karanjks** [comment]
Dear,

I give up bro sorry
if you get any solution in future please let me know please
Regards,
Karan Mehta

**Comment by Karanjks** [comment]
Dear,

I give up bro sorry
if you get any solution in future please let me know please

Regards,
Karan Mehta.

**Comment by ober01** [comment]
also every UITabBarItem has key value coding 

![keyvaluitem](https://user-images.githubusercontent.com/5435782/35664848-babe221c-0734-11e8-8c41-6354466e98c8.png)

**Comment by aju10** [comment]
Remove Pod, And just Drag and drop all the related files from their demo project,  then try, it will work

**Comment by BaluNaik** [comment]
@Karanjks @aju10 @PrakashMaharjan try this [NMAnimatedTabBarItem](https://cocoapods.org/pods/NMAnimatedTabBarItem)

**Comment by Thisismy0312** [comment]
> Remove Pod, And just Drag and drop all the related files from their demo project, then try, it will work

Thank you so much!!!
