### ISSUE TITLE
What should I set up when the selected picture is different from the ordinary one?

### ISSUE THREAD

**Issue by z234009184** [Ramotion/animated-tab-bar#209]
What should I set up when the selected picture is different from the ordinary one?

**Comment by z234009184** [comment]
who can help me..please

**Comment by ober01** [comment]
You can create custom animation behavior look for in readme https://github.com/Ramotion/animated-tab-bar#creating-custom-animations

**Comment by z234009184** [comment]
I can't find item in the custom animation because the selected picture is in the selected state of the item.

**Comment by z234009184** [comment]
The selected picture set in Storyboard does not work

**Comment by ober01** [comment]
Now you can set `var isHighlighted: Bool` property in custom animation

**Comment by z234009184** [comment]
Thank you for answering it for me！！！

After `func createCustomIcons(_ containers : NSDictionary)` add code `icon.highlightedImage = item.selectedImage?.withRenderingMode(renderMode)`  It's work!   But I modified the source code。。。

**Comment by ober01** [comment]
fix it in 3.0.4 version
