### ISSUE TITLE
Change tab programmatically

### ISSUE THREAD

**Issue by d4rkm1nd54** [Ramotion/animated-tab-bar#211]
Hi! I have to change de tab index when app starts, but i cant achieve it.
I tried:
```
let animatedTabBar = self.tabBarController as! RAMAnimatedTabBarController
animatedTabBar.setSelectIndex(from: self.tabBarController!.selectedIndex, to: 2)
```
And also with:
```
override func viewWillAppear(_ animated: Bool) {
        _ = self.tabBarController?.selectedIndex = 1
    }
```

But always fails. 

Thanks in advance!!

**Comment by UtkuDalmaz** [comment]
is this still failing?

**Comment by BaluNaik** [comment]
@d4rkm1nd54 @furiosFast @UtkuDalmaz I have faced the same kind of challenges with this library and created a simple one. Tyr this [NMAnimatedTabBarItem](https://cocoapods.org/pods/NMAnimatedTabBarItem)

**Comment by UtkuDalmaz** [comment]
@BaluNaik  amazing thanks

**Comment by UtkuDalmaz** [comment]
@BaluNaik screen goes black when I set tabbar item to nil

**Comment by PernicN** [comment]
same problem

**Comment by simformsolutions** [comment]
I am having the same issue, any update over this?

**Comment by 0ber** [comment]
please use this method https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L183
