### ISSUE TITLE
hidesBottomBarWhenPushed don't work 

### ISSUE THREAD

**Issue by kaich** [Ramotion/animated-tab-bar#213]
I use `hidesBottomBarWhenPushed = true `. But it doesn't work. I find your content is added to `View` of `UITabBarController`. And your custom container's height is 49. I think you can add container on tabbar. I change the source code as below.

```
    fileprivate func createViewContainer() -> UIView {
        let viewContainer = UIView()
        viewContainer.backgroundColor = UIColor.clear // for test
        viewContainer.translatesAutoresizingMaskIntoConstraints = false
        viewContainer.isExclusiveTouch = true
        tabBar.addSubview(viewContainer)
```

But new bug occurs.  Hope you  fix   hidesBottomBarWhenPushed bug

**Comment by xgoo** [comment]
Me too...

**Comment by ober01** [comment]
Duplicate of #144
