### ISSUE TITLE
Tab Bar item selected color issue

### ISSUE THREAD

**Issue by Shahbaz-Akram** [Ramotion/animated-tab-bar#215]
Please See it... 
![ezgif com-optimize](https://user-images.githubusercontent.com/8728903/38541677-452c5432-3cb9-11e8-927a-a501239d7fc7.gif)

**Comment by ober01** [comment]
it's standard behavior for RAMBounceAnimation. You could create your custom animation reed this: https://github.com/Ramotion/animated-tab-bar#creating-custom-animations
