### ISSUE TITLE
Configure Tab Bar Programmatically

### ISSUE THREAD

**Issue by tprasad23** [Ramotion/animated-tab-bar#219]
Hi !

I was curious if there was a way to change the animation from one set to another based on a changing state with in the app? We would like to have a dynamic alert embedded in our tab bar, so the animation would need to adapt. Is this possible?

**Comment by 0ber** [comment]
Yes, you could create own animation with the state, and change this state when you need. Look how to create custom animation https://github.com/Ramotion/animated-tab-bar#creating-custom-animations

**Comment by furiosFast** [comment]
How to set animations programmatically?

**Comment by 0ber** [comment]
You could this property https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L66
