### ISSUE TITLE
Reduce tab bar icon size

### ISSUE THREAD

**Issue by arshadsk5** [Ramotion/animated-tab-bar#220]
Hello, 
It is a very useful , i wanted to decrease the icon size's , can we reduce it. Please let me know it is an urgent requirement.
Thanks in advance.

**Comment by arshadsk5** [comment]
Hello Ober,
Can you please brief it.

**Comment by arshadsk5** [comment]
Thanks for your reply, can't we increase height of tab bar at the bottom ?

**Comment by 0ber** [comment]
No, we can't increase height of tab bar.

**Comment by arshadsk5** [comment]
ok anyhow thanks, i decreased the size of images.

**Comment by bchan930** [comment]
Is there a way to do this programmatically?
