### ISSUE TITLE
Always colors First Tab ICON when app launches!

### ISSUE THREAD

**Issue by dbspez** [Ramotion/animated-tab-bar#221]
It seems like it automatically changes its color to selected color on FIRST TAB ICON even though my default tab opened is 3rd tab(in the middle) when app is being launched.

Actually my app dynamically picks which tab to open depending on conditions when launching.

Is this coded in a way that it always colors the first tab icon no matter which tab was opened in the app launch?

Any quick fix solution in the code? Please let me know thanks

**Comment by 0ber** [comment]
to change tabs you need to use this method https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L183
