### ISSUE TITLE
Icon Color bug

### ISSUE THREAD

**Issue by Michele404** [Ramotion/animated-tab-bar#222]
let storyBoard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyBoard.instantiateViewController(withIdentifier: "TabBarController") as! UITabBarController
            vc.selectedIndex = 2
        self.present(vc, animated: true, completion: nil)

When I run this part of code it show me the controller n.2 in the RamAnimatedTabBar but it will show the icon n.0 in the RamAnimatedTabBar with another color instead of the n.2
Help?

**Comment by yusufkamilak** [comment]
Hello @Michele404, simply change following index `0` to the starting index you wish in `RAMAnimatedTabBarController.swift`
```
if 0 == index { // selected first elemet
    item.selectedState()
    container.backgroundColor = (items as [RAMAnimatedTabBarItem])[index].bgSelectedColor
}
```

**Comment by Michele404** [comment]
I am selecting the page with vc.selectedIndex = 2. Where I have to do your change, sorry?

**Comment by yusufkamilak** [comment]
You should change 0 to the index value of your starting tab

**Comment by Michele404** [comment]
1) If you do it all tab will got a color
2) You can’t pass data into cocoapods , you have to download it manually
