### ISSUE TITLE
纯代码怎么用啊   

### ISSUE THREAD

**Issue by lczalh** [Ramotion/animated-tab-bar#224]

**Comment by zhanglichuan** [comment]
let animation = RAMTransitionItemAnimations()
好像会报错
'RAMTransitionItemAnimations' initializer is inaccessible due to 'internal' protection level

**Comment by BaluNaik** [comment]
@zhanglichuan hey try this [NMAnimatedTabBarItem](https://cocoapods.org/pods/NMAnimatedTabBarItem)

**Comment by ieliwb** [comment]
牛逼中文，老外应该看不懂吧
