### ISSUE TITLE
Error selectedIndex at app lunch

### ISSUE THREAD

**Issue by furiosFast** [Ramotion/animated-tab-bar#225]
Hi,
there is a problem when i get the selectedIndex at first lunch of app.
The code is:
`guard let myTabBar = self.window?.rootViewController as? RAMAnimatedTabBarController else {
            return
        }
        print(myTabBar.selectedIndex)`
The code print "9223372036854775807"

**Comment by BaluNaik** [comment]
@furiosFast try [NMAnimatedTabBarItem](https://cocoapods.org/pods/NMAnimatedTabBarItem)

**Comment by 0ber** [comment]
Yes, you are right. But `selectedIndex` is the part of UITabBarController. And you can reproduce this issue with every UITabBarController. you need to create the issue in radar https://developer.apple.com/bug-reporting/
