### ISSUE TITLE
Animations don't work

### ISSUE THREAD

**Issue by sjking85** [Ramotion/animated-tab-bar#231]
I've followed your tutorial to the tee.

I have set the Tab Bar Controller to RAMAnimatedTabBarController.

I have set each individual tab bar item to RAMAnimatedTabBarItem.

I have added an object and hooked up the animation.

And it still doesn't work. Where am I going wrong?

**Comment by davidseek** [comment]
same issue here. 
can make it work programmatically. but not through storyboard

**Comment by sjking85** [comment]
David, I managed to get it working...

1. Set Tab Bar controller to RAMAnimatedTabBarController
2. Select tab bar item > Identity Inspector and set class to RAMAnimatedTabBarItem and module to RAMAnimatedTabBarController
3. Drag in your object and hook it up as per the video tutorial here: http://vimeo.com/112390386
4. Click the object and set class to (anything you want, e.g. RAMBounceAnimation) and ensure the module is RAMAnimatedTabBarController

For me, the issue was that it wasn't setting the module in the identity inspector on the animation object. Also make sure you set a duration on the object attribute inspector and press enter.

Give that a whirl to see if it fixes your issue too.

**Comment by davidseek** [comment]
Yeah. I have noticed that the module is not set automatically. That was the issue for me.
But I went ahead and ripped this baby apart and instead of using animation outlet, i have hardcoded the animation as a lazy var. works fine for me.

**Comment by sjking85** [comment]
And to be fair, probably a better option.

Good work, glad you've got it working.

**Comment by BaluNaik** [comment]
@sjking85 @davidseek try this [NMAnimatedTabBarItem](https://cocoapods.org/pods/NMAnimatedTabBarItem)

**Comment by emresancaktar** [comment]
Check your TabbarController Module it should be "RAMAnimatedTabBarController"

**Comment by furiosFast** [comment]
same issue, but all module are set!

**Comment by 0ber** [comment]
check my demo it works https://github.com/0ber/AnimatedTabBar-Pod-Test

**Comment by RuchiMakadia** [comment]
> David, I managed to get it working...
> 
> 1. Set Tab Bar controller to RAMAnimatedTabBarController
> 2. Select tab bar item > Identity Inspector and set class to RAMAnimatedTabBarItem and module to RAMAnimatedTabBarController
> 3. Drag in your object and hook it up as per the video tutorial here: http://vimeo.com/112390386
> 4. Click the object and set class to (anything you want, e.g. RAMBounceAnimation) and ensure the module is RAMAnimatedTabBarController
> 
> For me, the issue was that it wasn't setting the module in the identity inspector on the animation object. Also make sure you set a duration on the object attribute inspector and press enter.
> 
> Give that a whirl to see if it fixes your issue too.

also, work for me

**Comment by aitadeta1314** [comment]
> David, I managed to get it working...
> 
> 1. Set Tab Bar controller to RAMAnimatedTabBarController
> 2. Select tab bar item > Identity Inspector and set class to RAMAnimatedTabBarItem and module to RAMAnimatedTabBarController
> 3. Drag in your object and hook it up as per the video tutorial here: http://vimeo.com/112390386
> 4. Click the object and set class to (anything you want, e.g. RAMBounceAnimation) and ensure the module is RAMAnimatedTabBarController
> 
> For me, the issue was that it wasn't setting the module in the identity inspector on the animation object. Also make sure you set a duration on the object attribute inspector and press enter.
> 
> Give that a whirl to see if it fixes your issue too.

also, change the module to RAMAnimatedTabBarController. its good job.
