### ISSUE TITLE
hidesBottomBarWhenPushed = true  icon not show

### ISSUE THREAD

**Issue by kaich** [Ramotion/animated-tab-bar#232]
When I push vc2 from vc1. I set `vc2.hidesBottomBarWhenPushed = true`.  And In `viewWillDisappear` I set `animationTabBarHidden(false)`. I get only a blank tabbar. there are no any icon and title.

**Comment by idroxid** [comment]
@kaich I have exactly the same issue.
Just to be sure we're facing the same thing:
Can you please try to start your app, tap on tab items (important to do this as the very first action) and then go to the right tab item, nav to vc2 and go back to vc1 ?
Doing this, the tabbar is working as expected.
This is not a solution, only a way to be sure we're on the same problem.

Cheers

**Comment by kaich** [comment]
@idroxid Sorry, I have given up. I used the `UITabBarController` instead. I think it based on ios version. The tabbar behavior has changed. I think it works fine at past.

**Comment by idroxid** [comment]
@kaich same decision here ;)

**Comment by 0ber** [comment]
use this method https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L165 for the hiding navigation bar
