### ISSUE TITLE
Dynamically change items in animated tab bar

### ISSUE THREAD

**Issue by luibo** [Ramotion/animated-tab-bar#234]
Hi everyone, 

I'm developing an app that provides different UIs based on the kind of user that is logged in, so based on that the tab bar must show different items (actually the items are always the same, but depending on the user type the bar must show all items, two or three of them); I've tried to dynamically modify the items array simply using the remove(atIndex: Int) swift function, but the app crashes as that kind of operation is not allowed. I even tried to work with the overridden setViewControllers function, but it appears to not be called. Is there a way to dynamically edit the array of items/controllers used by the animated tab bar?
Thank you in advance for your help

**Comment by luibo** [comment]
mocc a chivemmuort putivn risponnr ind e fess re mamm vost

**Comment by khoren93** [comment]
Hi @luibo 
Please check this project, is this what you wanted?
https://github.com/khoren93/SwiftHub

**Comment by 0ber** [comment]
I created the branch where I remove the items and it works https://github.com/Ramotion/animated-tab-bar/tree/tests/remove-tabs
