### ISSUE TITLE
animationTabBarHidden in iOS 12

### ISSUE THREAD

**Issue by furiosFast** [Ramotion/animated-tab-bar#235]
Hi,
the function animationTabBarHidden(true) doesn't work in iOS 12
There are other with same problem?

**Comment by StanislavCekunov** [comment]
Here is my solution for now:
1. Using Notification Center to post status of the tabBar:
`NotificationCenter.default.post(name: "notificationHideTabBar", object: nil, userInfo: ["isHidden": true])`


2. Add observer to catch that in main TabBarController
```
NotificationCenter.default.addObserver(forName: "notificationHideTabBar, object: nil, queue: OperationQueue.main, using: { (notification) in
            if let isHidden = notification.userInfo?["isHidden"] as? Bool {
                self.animationTabBarHidden(isHidden)
            }
        })
```

Hope it helps ;)

**Comment by furiosFast** [comment]
same problem.
when I lunch the code to hide the tab bar
`myTabBar.animationTabBarHidden(true)`
the tab bar items disappear but not the tab bar and therefore remains a black line
