### ISSUE TITLE
how I can make tabBar.isHidden here ??

### ISSUE THREAD

**Issue by Rehamsa3d** [Ramotion/animated-tab-bar#239]
//self.tabBarController?.tabBar.isHidden = true 
don't work ??

**Comment by Yonodactyl** [comment]
For the purpose of ruling out the possible, do you have that actually commented out in your source code? It should not include the // in front of self.tab....

**Comment by Rehamsa3d** [comment]
> For the purpose of ruling out the possible, do you have that actually commented out in your source code? It should not include the // in front of self.tab....

yea of course I mean self.tabBarController?.tabBar.isHidden = true
can you help me to solve this issue please??

**Comment by 0ber** [comment]
use this public method to hide tabBar https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L165
