### ISSUE TITLE
How to make center uitabbar button raised as show in dribble gif 

### ISSUE THREAD

**Issue by neoD1** [Ramotion/animated-tab-bar#24]

**Comment by ober01** [comment]
Need change constant in icon constraint 

let item: RAMAnimatedTabBarItem = self.tabBarItem as! RAMAnimatedTabBarItem
        for constraint in (item.iconView!.icon.superview?.constraints)! {            
            if let currentView: UIImageView = constraint.firstItem as? UIImageView {
                if item.iconView!.icon == currentView {
                    if constraint.firstAttribute == .CenterY {
                        constraint.constant = -10;
                    }
                }
            }
        }

**Comment by embassem** [comment]
May this be a @IBInspectable ?
