### ISSUE TITLE
Type 'CAAnimationCalculationMode' (aka 'NSString') has no member 'cubic'

### ISSUE THREAD

**Issue by wawilliams003** [Ramotion/animated-tab-bar#240]
Hi, thanks for this wonderful library. Since I updated Xcode to the current Xcode 10 I am getting some errors. I am using swift 4.

ERRORS: 
Type 'CAMediaTimingFillMode' (aka 'NSString') has no member 'removed'
Type 'CAAnimationCalculationMode' (aka 'NSString') has no member 'cub

I am using the latest version of the framework, thank you!

**Comment by BeamerCola** [comment]
Any luck with this?

**Comment by wawilliams003** [comment]
> Any luck with this?

Try updating pods, or remove and install framework did it for me.

**Comment by reshmaraghu** [comment]
Updated the pods... My project still seems to have the issue... :(

**Comment by arshadsk5** [comment]
I am using Swift 4.2, xcode 10. even i am getting same problem, any help please

**Comment by 0ber** [comment]
works on swift 5.0, Xcode 10.2 check my demo https://github.com/0ber/AnimatedTabBar-Pod-Test

**Comment by SBlincov** [comment]
Use:
kCAFillModeRemoved instead CAMediaTimingFillMode.removed
and
kCAAnimationCubic instead CAAnimationCalculationMode.cubic
