### ISSUE TITLE
Problem with select tabBarItem

### ISSUE THREAD

**Issue by vitali36** [Ramotion/animated-tab-bar#242]
Problem if i tap on first tabaritem from any other. TabBarItem not selecting. Also there's a problem when I tap on the view of my ViewController (tabbarcontroller always selects the first tabBarItem). Your demo project has  a same problem.

**Comment by 0ber** [comment]
It works correctly on my demo project, please check  https://github.com/0ber/AnimatedTabBar-Pod-Test/tree/feature/SelectedItem
