### ISSUE TITLE
RamAnimatedTabBar crashed my app when I turn to landscape

### ISSUE THREAD

**Issue by matvdg** [Ramotion/animated-tab-bar#243]
My app is only in portrait mode, except for a single view overriding the orientationLock to .allButUpsideDown.

I don't know yet if it's since a new version of your library, or if it's since the introduction of iOS 12 or the new Swift 4.2.1/Xcode 10.1, but when I turn my iPhone in landscape mode, the lib crashes. I found the bug by creating a breakpoint exception with the debugger command $po arg1 to find who was crashing my app, since I changed nothing and it was working fine before when turning to landscape.

The debugger output is : 
`Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x6000031bcc80 "UIView:0x7ffd03054db0.bottom"> and <NSLayoutYAxisAnchor:0x6000031bce00 "_UILayoutSpacer:0x6000014bf1b0'UIVC-bottomLayoutGuide'.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.`

<img width="1420" alt="screenshot 2018-11-05 at 16 50 48" src="https://user-images.githubusercontent.com/6815241/48009126-5159b400-e11b-11e8-8560-c493d06f1c54.png">

**Comment by saeid** [comment]
+1

**Comment by tsulok** [comment]
I'm experience the same issue on xcode 10.2 with SDK version 4.0.2 and 5.0.0
Previously I've used 4.0.0 on Xcode10.1 without any problem.

**Comment by 0ber** [comment]
I can't reproduce the issues in my demo project https://github.com/0ber/AnimatedTabBar-Pod-Test. Could you add PR to this demo project where reproduce this issue

**Comment by cuibeihong** [comment]
+1
