### ISSUE TITLE
RAMAnimatedTabBar issue when change direction

### ISSUE THREAD

**Issue by abdalwhabmalkawi** [Ramotion/animated-tab-bar#244]
hi guys
in my app I use the animated tab bar
and I use the localization in my app to Arabic language
but the issue when I change the language throw run app
the tab bar direction not change (RTL)

**Comment by 0ber** [comment]
Why do you need RTL? The `textAlignment` `TabBarItem Label` is center and direction not change in Arabic localization. Look the test project with localization https://github.com/0ber/AnimatedTabBar-Pod-Test/tree/feature/Localization
