### ISSUE TITLE
My selected state image becomes blue

### ISSUE THREAD

**Issue by iamsanketray123** [Ramotion/animated-tab-bar#245]
I even added the selected Image, but it still doesn't show up. Rather it looks like this when selected. 
<img width="765" alt="screen shot 2018-11-18 at 7 58 29 pm" src="https://user-images.githubusercontent.com/17732307/48673903-72cf8c80-eb6c-11e8-92a8-46a289033dcf.png">

**Comment by iamsanketray123** [comment]
My image was not set to 'use original'

**Comment by HadiYaac** [comment]
@iamsanketray123 what do you mean by 'use original'? How was that fixed??
