### ISSUE TITLE
Add animations programmatically

### ISSUE THREAD

**Issue by furiosFast** [Ramotion/animated-tab-bar#246]
hi,
is possible to add animation to tabbaritem programmatically and not from storyboard?

**Comment by 0ber** [comment]
let item = RAMAnimatedTabBarItem()
item.animation = __ANIMATION___
look https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L66

**Comment by furiosFast** [comment]
Hello and thanks for the reply.
I (where I followed the whole procedure you described to implement the library) in the Delegate app I added the following code, but I still don't get any animation

```
guard let myTabBar = self.window?.rootViewController as? RAMAnimatedTabBarController else { return }
myTabBar.animatedItems[0].title = loc("tab_SCALE
myTabBar.animatedItems[0].image = UIImage(named: "icons8-moleskine-filled")        myTabBar.animatedItems[0].animation = RAMBounceAnimation()

myTabBar.animatedItems[1].title = loc("tab_ROSA")
myTabBar.animatedItems[1].image = UIImage(named: "icons8-wind-rose-filled")
myTabBar.animatedItems[1].animation = RAMRightRotationAnimation()

myTabBar.animatedItems[2].title = loc("tab_PREVISIONI")
myTabBar.animatedItems[2].image = UIImage(named: "icons8-windsock-filled")
myTabBar.animatedItems[2].animation = RAMBounceAnimation()
```

**Comment by 0ber** [comment]
I check, it works look for https://github.com/0ber/AnimatedTabBar-Pod-Test/commit/60219c91f80e629c4143610d20daf2f4862fd2e7 branch https://github.com/0ber/AnimatedTabBar-Pod-Test/tree/feature/animations_programmatically_246

**Comment by huylv-teko** [comment]
> I check, it works look for [0ber/AnimatedTabBar-Pod-Test@60219c9](https://github.com/0ber/AnimatedTabBar-Pod-Test/commit/60219c91f80e629c4143610d20daf2f4862fd2e7) branch https://github.com/0ber/AnimatedTabBar-Pod-Test/tree/feature/animations_programmatically_246

so we can not set animation programmatically without edit source, can we?
