### ISSUE TITLE
Support Swift 5

### ISSUE THREAD

**Issue by ascentman** [Ramotion/animated-tab-bar#247]
**Environment**

Xcode Version: 10.2
Swift Version: 5

**Goals**
Swift 5 support for the framework

**Expected Results**
No warning to convert RAMAnimatedTabBarController to Swift 5

**Actual Results**
Xcode created warnings to convert RAMAnimatedTabBarController to Swift 5

**Steps to Reproduce**
Build the cocoapod in Xcode 10.2

**Code Samples & Details**
Run any project depending on the pod's in Xcode 10.2 to see the warning.

**Comment by 0ber** [comment]
the project is already converted to swift 5. https://github.com/Ramotion/animated-tab-bar/commit/dacd232c4ee86df6156210a253fe6268b2d779d2

look version 5.0.0

**Comment by 0ber** [comment]
I create a quick example, I hope it's help https://github.com/0ber/AnimatedTabBar-Pod-Test
