### ISSUE TITLE
App Crashes on setSelectedIndex Method call programmatically to select an index.

### ISSUE THREAD

**Issue by amit2908** [Ramotion/animated-tab-bar#248]
In file RAMAnimatedTabBarController+BottomLine.swift

       `func setBottomLinePosition(index: Int, animated: Bool = true) {
             guard let itemsCount = tabBar.items?.count, itemsCount > index,
             let currentItem = (containers.filter { $0.value.tag == index}).first?.value else { return }
             lineLeadingConstraint?.isActive = false
        
             lineLeadingConstraint = bottomLine?.leadingAnchor.constraint(equalTo: currentItem.leadingAnchor)
             lineLeadingConstraint?.isActive = true
        
        if animated {
            UIView.animate(withDuration: bottomLineMoveDuration) { self.bottomLine?.superview?.layoutIfNeeded()  
                     // **App crashed on this line with EXC_BAD_ACCCESS(code=2, address=)** 
                 }   
                       } else {
                    self.bottomLine?.superview?.layoutIfNeeded()
                 }
                }`

**Comment by 0ber** [comment]
It works well, could you check the example https://github.com/0ber/AnimatedTabBar-Pod-Test/commits/master, commit https://github.com/0ber/AnimatedTabBar-Pod-Test/commit/ee81955ddf59b16476fc09e72d2c28d9417eaf28
