### ISSUE TITLE
Unable to make tabs animated when added through Pod

### ISSUE THREAD

**Issue by jarrarhaider** [Ramotion/animated-tab-bar#249]
I have added using pod. Followed every step but can't animate the tabs. I downloaded the project and found that tab user controller is inherited from Animated Tab Bar. This is the only difference I could find. Can someone tell how to use animations if included using pod

**Comment by 0ber** [comment]
I create quick example, I hope it is help https://github.com/0ber/AnimatedTabBar-Pod-Test

**Comment by jarrarhaider** [comment]
Thank you
