### ISSUE TITLE
animationTabBarHidden black space ios 12

### ISSUE THREAD

**Issue by fenixsolorzano** [Ramotion/animated-tab-bar#252]
I tried to hide the tab bar in `viewWillAppear` by casting the tabBarController to RAMAnimatedTab... using `animationTabBarHidden` and show it back when `viewWillDissapear`. It hides, but leaves a black space.
![IMG_1337ED2FAC09-1](https://user-images.githubusercontent.com/15699775/55899731-bd38c080-5b82-11e9-846b-54fca66a7bd3.jpeg)

**Comment by 0ber** [comment]
you also set `hidesBottomBarWhenPushed` to `true`

**Comment by mayankwadhwa111** [comment]
does not work Please?

**Comment by fenixsolorzano** [comment]
If I set the `hidesBottomBarWhenPushed ` to `true` and the tab bar appear again the bar items go behind the bar @0ber

**Comment by fenixsolorzano** [comment]
Why did you close it @0ber? It doesn't work

**Comment by 0ber** [comment]
Look for example it works https://github.com/0ber/AnimatedTabBar-Pod-Test/tree/feature/HideTabBar
