### ISSUE TITLE
Selected/unselected colors not changing

### ISSUE THREAD

**Issue by fenixsolorzano** [Ramotion/animated-tab-bar#253]
I'm trying to set `unselectedItemTintColor` and item `iconColor` but they're not working, the item color doesn't change when selected, just the text, I set the selected and unselected state images but it doesn't work

**Comment by Jigneshiosdeveloper** [comment]
I also trying to set "The color of the UITabBarItem text" -> open var textColor: UIColor = UIColor.black(RAMAnimatedTabBarController.swift). 
i want to change another color instead of black. And also want to selected color from blue(default color) to any another color. i tried but it doesn't work

**Comment by 0ber** [comment]
use this  https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMItemAnimationProtocol.swift#L56-L59 properties to change selected color for text and icon.

![image](https://user-images.githubusercontent.com/5435782/57210478-72756180-6fe5-11e9-901c-449bbf285cda.png)

**Comment by fenixsolorzano** [comment]
I create my tab bar by code, how should I do that in code?
