### ISSUE TITLE
Custom item size

### ISSUE THREAD

**Issue by RishatYakushev** [Ramotion/animated-tab-bar#256]
Custom item size

**Comment by RishatYakushev** [comment]
I found a solution to the problem, you can close it, it can help someone:)
yourItem.animation.iconSelectedColor = UIColor.yourColor
yourItem.animation.textSelectedColor = UIColor.yourColor

**Comment by RishatYakushev** [comment]
let purchaseHistoryItemImage = UIImage(named: "PurchaseHistoryIcon")?.af_imageScaled(to: CGSize(width: 25, height: 25))
        
        let purchaseHistoryItem = RAMAnimatedTabBarItem(title: "History", image: purchaseHistoryItemImage, tag: 0)
        purchaseHistoryItem.animation = RAMBounceAnimation()

Cropping the image does not give the result, how can i set the image size of the tab bar icon programmatically?

**Comment by 0ber** [comment]
@RishatYakushev hi,  You can't change the image size now. But you can look to the code and implement it. look to the code https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L360
