### ISSUE TITLE
Initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by Senhelee** [Ramotion/animated-tab-bar#257]
When I type in this line, I got this error below

let animation = RAMTransitionItemAnimations()
Error: 'RAMTransitionItemAnimations' initializer is inaccessible due to 'internal' protection level

**Comment by igork-ramotion** [comment]
Works fine, RAMAnimatedTabBarController even doesn't override any initializer so all parent initializers are available :)
