### ISSUE TITLE
How to set up Left and right layout？

### ISSUE THREAD

**Issue by cuibeihong** [Ramotion/animated-tab-bar#258]
device： iPad  iOS11+
like this:
<img width="925" alt="屏幕快照" src="https://user-images.githubusercontent.com/18608903/64750426-7abd4a80-d54b-11e9-96b7-eca36053bb99.png">

**Comment by igork-ramotion** [comment]
Right now library doesn't support this layout, to implement this at first you can take a look at createConstraints function there layout magic happen: https://github.com/Ramotion/animated-tab-bar/blob/3fc716a0a6e15ed3488ebe6e2721cc7cab83426e/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift#L391 

You can add xOffset to `RAMAnimatedTabBarItem`, but you will need to support it in different places.
