### ISSUE TITLE
Tabbar Not hide 

### ISSUE THREAD

**Issue by RuchiMakadia** [Ramotion/animated-tab-bar#261]
I tried to show Viewcontroller using navigation viewController now when I push to Second View controller from First Viewcontroller that contain a bottom tab bar. 
I used code like below in second ViewController ViewWillAppear Method
` let tababrController = RAMAnimatedTabBarController()
  `tababrController.tabBar.isHidden` = true`

here is a screenShot of my storyBoard 
[https://prnt.sc/passk4](url)

I also check the right of Hide Bottom Bar on Push in Second View Controller 
here is a second view Controller image that contain bottom bar 
[https://prnt.sc/pasyg9](url)
please help me thanx in advance

**Comment by Yarob50** [comment]
I have the same issue here :(

**Comment by Yarob50** [comment]
I am not sure whether this behavior is related to ios 13, but anyways, I found a simple solution for it:
In viewWillApper of the ViewController that you want to hide the tabbar when it's presented:
`override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        //hide the tabbar
        if let tb = self.tabBarController as? RAMAnimatedTabBarController{
            tb.animationTabBarHidden(true)
        }
    }`
And then in ViewWillDisappear:
`override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        //showing the tabbar again
        if let tb = self.tabBarController as? RAMAnimatedTabBarController{
            tb.animationTabBarHidden(false)
        }
    }`
I hope it works with anyone having the problem :)
