### ISSUE TITLE
Crash in RAMAnimatedTabBarController init process (5.1.0)

### ISSUE THREAD

**Issue by Nightstep** [Ramotion/animated-tab-bar#268]
Xcode version: 11.1
Library version: 5.1.0
Crash on `RAMAnimatedTabBarController.init()`

Good day,
Getting crash in RAMAnimatedTabBarController init call. The thing is tab bar immediately calls  `viewDidLoad()` method, which calls `initializeContainers()`. The line 135 expects that tabbar.items is in range 0..5, but it's always `nil`. Thats why it always throws `fatalError("More button not supported")`
There's no other initializers with containers injection as well. (`init(tabs: [UIViewController])`)

Code snipper which causes fatal error:
```
    // MARK: create methods
    private func initializeContainers() {
        guard let items = tabBar.items, items.count <= 5 else {
            fatalError("More button not supported")
        }
```

**Comment by igork-ramotion** [comment]
@Nightstep It happen because you need to assign `viewControllers` before add TabBarController into view hierarchy. I've improve error handling for that case, so now it will not crash. But still for correct work you need to assign your tab view controllers

**Comment by Nightstep** [comment]
It crashes right on `init()` call. There's no way to add viewControllers because the compiler just doesn't go to the next line of execution.
