### ISSUE TITLE
Bottombar not display proper in iPhone 11 pro max 

### ISSUE THREAD

**Issue by codal-jayeshk** [Ramotion/animated-tab-bar#270]
Hello

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-15 at 14 30 02](https://user-images.githubusercontent.com/52558720/68931932-93e6af80-07b7-11ea-97e2-4e4c449af90f.png)
Bottombar is not display on bottom accordingly to safe area in iPhone 11 pro max.

**Comment by igork-ramotion** [comment]
@codal-jayeshk Hey!) This is not a bug, we think that it looks better at the bottom. 
If you want to put `bottomLine` above safe area you can fork and change 
From:
`bottomLine?.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true`
To: 
```
if #available(iOS 11.0, *) {
    bottomLine?.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor).isActive = true
} else {
    bottomLine?.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
}
```
