### ISSUE TITLE
How to adjust the gap between icon and title in item, thank you

### ISSUE THREAD

**Issue by BeingCode** [Ramotion/animated-tab-bar#273]
<img width="536" alt="A527C928-0105-48D1-BDD9-D0075460D191" src="https://user-images.githubusercontent.com/44461496/69045812-9c96ea00-0a32-11ea-8e4e-408c4339104e.png">

**Comment by igork-ramotion** [comment]
@BeingCode hey!) You can take a look at UITabBarItem variable `titlePositionAdjustment`. But it will adjust both icon and title position (Apple do the same)

If you want to change space you can use this constants. Hope it will help 🤞🏻  
```
public static let defaultTitleVerticalOffset: CGFloat = 10
public static let defaultIconVerticalOffset: CGFloat = -5
```

**Comment by BeingCode** [comment]
@igork-ramotion The middle picture is large. I want to move the raised display upward without blocking the text below

**Comment by igork-ramotion** [comment]
@BeingCode Currently library doesn't support that functionality, but if you want you can add it by yourself  
The starting point may be the function `func layoutContainers() ` there all layout items calculation happen

**Comment by BeingCode** [comment]
@igork-ramotion I adjusted the position of the icon, but the raised part of the item in the middle couldn't respond, thank you￼￼￼￼￼

**Comment by BeingCode** [comment]
@igork-ramotion 
![13051574155848_ pic](https://user-images.githubusercontent.com/44461496/69134381-5bfea580-0af2-11ea-8c5e-4dc7119c20d2.jpg)

**Comment by igork-ramotion** [comment]
@BeingCode you need to handle interaction on that item separately (maybe by using custom button or by gesture recogniser). Library doesn't support this functionality
