### ISSUE TITLE
How do I set the text color ?

### ISSUE THREAD

**Issue by EONCorp** [Ramotion/animated-tab-bar#276]
How do I set the text color of the selected item?
Now I can set the icon color of the selected item, but the text color remains by default. 
<img width="476" alt="Снимок экрана 2020-01-13 в 18 38 38" src="https://user-images.githubusercontent.com/43572030/72363271-37dbd100-36fd-11ea-994b-a2c6b8870529.png">

**Comment by igork-ramotion** [comment]
`RAMItemAnimation` has inspectable properties `textSelectedColor` `iconSelectedColor`.
To change default state color use `RAMAnimatedTabBarItem` properties `textColor` and `iconColor`
