### ISSUE TITLE
update to Swift 2.0

### ISSUE THREAD

**Issue by andersonkxiass** [Ramotion/animated-tab-bar#28]
Hi, I'm getting errors in Xcode 7. Do you have plans to update to Swift 2.0?

Thanks

**Comment by jonahneugass-ck** [comment]
Swift 2.0 is in beta, an upgrade would mean that it couldn't be used in production apps.

**Comment by thediary** [comment]
Perhaps a second branch could be created like many third party libraries and open source projects are doing during this period? Swift 2.0 is in beta, but if developing in Xcode 7 is still a must!

**Comment by ADevelopStudio** [comment]
I'm using current build with Swift 2.0 - works Fine! Thanks!
