### ISSUE TITLE
Animates two items at the same time

### ISSUE THREAD

**Issue by sthyuji** [Ramotion/animated-tab-bar#283]
If I select first item, first and second item animates at the same time in example.
Example link is here: https://github.com/0ber/AnimatedTabBar-Pod-Test
For this reason, My app development has been disrupted.
Swift 5

**Comment by igork-ramotion** [comment]
@sthyuji Hey, this is not a problem of `Animated-tab-bar` sources, this is a problem of provided example

to prevent second item animation just remove code in ViewController.swift 

```
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)    
    (tabBarController as! RAMAnimatedTabBarController).setSelectIndex(from: 0, to: 1)
}
```
