### ISSUE TITLE
How to prohibit pictures from rendering

### ISSUE THREAD

**Issue by nilhy** [Ramotion/animated-tab-bar#285]
###  How to prohibit pictures from rendering ? 

my need is to not need pictures for color rendering, only animation

`image.tintColor == none`

Please tell me how to do it ,thanks.

**Comment by igork-ramotion** [comment]
@nilhy Hey, if I understand you right you can use `isHidden` or use empty UIImage to hide image in `RAMAnimatedTabBarItem`. If that doesn't help you please provide more information and reopen this issue
