### ISSUE TITLE
RTL not supported? 

### ISSUE THREAD

**Issue by oenama** [Ramotion/animated-tab-bar#286]
Please check this video (RAMAnimatedTabBarDemo Localized) : 

[![RTL issue](https://user-images.githubusercontent.com/11976534/82328130-2591dc80-99e8-11ea-8a69-208f1b479c1a.png)](https://www.dropbox.com/s/4txn7ibiz5jomhw/Screen%20Recording%202020-05-19%20at%203.34.01%20PM.mov?dl=0)

**Comment by igork-ramotion** [comment]
@oenama Please check v 5.2.0. Thank You for reporting this bug
