### ISSUE TITLE
Hiding tabbar issue

### ISSUE THREAD

**Issue by Maulik9110** [Ramotion/animated-tab-bar#289]
If tried hiding with below code,

let animatedTabBar = self as? RAMAnimatedTabBarController
animatedTabBar?.animationTabBarHidden(!visible)

in the next screen it appears the full black tabbar.

And if tried using,
viewController.hidesBottomBarWhenPushed = true
then it works like a charm but the problem is after coming back to the previous screen tab icons just disappears.

xcode: 11.0
swift: 4.2

Any solution for this??

**Comment by igork-ramotion** [comment]
@Maulik9110 Hey! Please take a look at `hide-tab-bar-example`.  For me it work fine in both scenarios.  
Reopen this issue if you still have problems with hiding tab bar also in that case please specify what iOS version you use.  
Also you can provide your example code to reproduce this issue
