### ISSUE TITLE
TabBarItem text color doesn't obey the tint color when selected

### ISSUE THREAD

**Issue by jmhirsch** [Ramotion/animated-tab-bar#290]
Hello,

In implementing the animated tab bar, I'm facing difficulty getting the text color of the tabbaritem to match the rest of the UI.
The originally selected tabbaritem will begin with the correct color (in this case systemIndigo), however upon selecting another tab, it reverts to the default systemBlue color. The button's color also does not fade to gray when a modal view controller is presented

Note the 'Media' tab bar item on the bottom left of the images below. The correct color should be systemIndigo when selected, and systemGray when deselected / in the background. In both cases, it is systemBlue

Additionally, it would be nice to be able to position the text label on the side of the icon on iPad like the original TabBarViewController does

![IMG_0098](https://user-images.githubusercontent.com/54959558/91498219-3cac5a00-e874-11ea-8a77-e069393d9920.png)

![IMG_0097](https://user-images.githubusercontent.com/54959558/91498107-0969cb00-e874-11ea-9749-eb99d156a5bb.png)

**Comment by igork-ramotion** [comment]
@flynn-buc hey, please take a look at RAMItemAnimation it has
`@IBInspectable open var textSelectedColor: UIColor`
`@IBInspectable open var iconSelectedColor: UIColor`

To update unselected state you can use RAMAnimatedTabBarItem
`@IBInspectable open var textColor: UIColor`
`@IBInspectable open var iconColor: UIColor`

Hope this would help you 🤞🏻
