### ISSUE TITLE
Demo is not working 

### ISSUE THREAD

**Issue by amrangry** [Ramotion/animated-tab-bar#291]
Demo is not working

**Comment by igork-ramotion** [comment]
@amrangry hey, could you please describe what exactly doesn't work ? I've just try code from `master` on simulator and on device and it works fine. Please provide more information and if problem is still actual reopen this issue

**Comment by amrangry** [comment]
thanks, @igork-ramotion for your response 
its works fine now with me the problem with inherit from the module actually 

![image](https://user-images.githubusercontent.com/2900952/92483720-3619cd00-f1fa-11ea-9fb0-7e70727a7d26.png)
