### ISSUE TITLE
Issue with icon color

### ISSUE THREAD

**Issue by chenk1** [Ramotion/animated-tab-bar#30]
Hi, 
I'm having a little issue with the icon's color.
Before a tab bar is selected, its icon's color is wrong.

For example: my TextColor is dark grey, and my TextSelectedColor and IconSelectedColor are white.
Before I select a tab bar it appears with dark grey text (which is correct) and white icon (which is wrong).

![screen shot 2015-06-15 at 9 33 11 am](https://cloud.githubusercontent.com/assets/8477181/8154435/d7f4af1a-1342-11e5-9a31-7072d47c1a53.png)

Have I configured something wrong? Or is it a bug?
Thanks!

**Comment by carolinapocket** [comment]
I'm having the same issue 😑

**Comment by aramikg** [comment]
I'm having a similar issue... All by icons are blue and text are black.  when I first run the app the selected icon is black instead of blue.  When I go to another tab then it fixes itself.

**Comment by aalzanki** [comment]
I fixed this in my fork and sent a pull request. For the meantime, here it is: https://github.com/aalzanki/animated-tab-bar

**Comment by annehiro** [comment]
There are a lot of changes in your fork that are not needed for this fix.

Here is the fix. Go into RAMAnimatedTabBarController.swift. 
1. Set your deselected color @IBInspectable var textColor = myDeselectedColorWhichIsLikelyAShadeOfGray
2. Replace the following code: 

                let icon = UIImageView(image: item.image)
                icon.translatesAutoresizingMaskIntoConstraints = false
                icon.tintColor = UIColor.clearColor()

With this: 


                let renderImage = item.image?.imageWithRenderingMode(.AlwaysTemplate)
                let icon = UIImageView(image: renderImage)
                icon.translatesAutoresizingMaskIntoConstraints = false
                icon.image = renderImage
                icon.tintColor = item.textColor

**Comment by trungnguyen1791** [comment]
Actually those change only fixes "rotation item" color. With other type of animations. Its doesn't work :(

**Comment by muhasturk** [comment]
This problem is still here

**Comment by ober01** [comment]
Fixed

**Comment by peebits** [comment]
i want to change selected image of tab bar item. In fact i had applied tabbar.selected Image Property

**Comment by YERUVAKONIREDDY** [comment]
I am not getting what people are saying .I have two assets not selected and selected icons for Tab Bar Item Images .I am adding selected image and unselected image to the Tab bar item but after running I am getting selected image colour changing.i checked my assets I don't have that king of blue colour selected asset mine is pink colour 
![assets](https://user-images.githubusercontent.com/30068182/35766514-33ff1cd6-0900-11e8-991c-59072241a32a.png)
![selected](https://user-images.githubusercontent.com/30068182/35766515-343b9f1c-0900-11e8-9606-b1c1feeacc4b.png)
![unselected](https://user-images.githubusercontent.com/30068182/35766516-3477f0de-0900-11e8-91ea-efde4583bed9.png)


can you help me is anything wrong
