### ISSUE TITLE
iOS 16 crashes

### ISSUE THREAD

**Issue by astrokin** [Ramotion/animated-tab-bar#305]
```Fatal Exception: NSInternalInconsistencyException
Inconsistency in UITabBar items and view controllers detected. 
No view controller matches the UITabBarItem '<RAMAnimatedTabBarController.RAMAnimatedTabBarItem: 0x155142b80> title='' selected'.

**Comment by resand** [comment]
How is your implementation? With code, SB or XIB?

The same thing happened to me but with the code implementation and embedding a UINavigationController.

**Comment by astrokin** [comment]
this happened to me because i've wrapped  into `UINavigationController` my each tab item after assign `tabBarItem`. So if you are using `UINavigationController` you must set `RAMAnimatedTabBarItem` property to exactly each `UINavigationController` you are passing into ```func setViewControllers(_ viewControllers: [UIViewController]?, animated: Bool)```

**Comment by resand** [comment]
You need to add the Bar Item tab like in the example here:

https://github.com/Ramotion/animated-tab-bar/issues/86

It's in an older version of Swift, but it's the idea and it works perfectly.
