### ISSUE TITLE
Badge position

### ISSUE THREAD

**Issue by benjaminhorner** [Ramotion/animated-tab-bar#33]
I tried adding a badge to the RAMAnimatedTabBarItem and it is offset. Instead of sticking to the right it sticks to the left. Furthermore, it appears BEHIND the icon.

**Comment by nassarofficial** [comment]
same issue here...

**Comment by benjaminhorner** [comment]
It appears Apple uses the UIImage to position the badge. But in the case of a RAMAnimatedTabBarItem, the UIImage is replaced with a UIView. Therefore, the badge positions itself to the left. You can see this by adding a badge to a TabBarItem with no image.

As for the badge being behind, I guess that comes simple from the fact the UIView that comes in replacement of the UIImage is not sent to the back of the stack.

I found a rather nice way of getting around this issue using your own UILabel for the badge, and positioning it yourself. Maybe this could be added as default behavior to the RAMAnimatedTabBar ?

**Comment by GuyKahlon** [comment]
Hi @benjaminhorner, can you share the code please?

**Comment by ober01** [comment]
I fixed badge in version 1.0.5
