### ISSUE TITLE
Cannot set tintColor

### ISSUE THREAD

**Issue by benjaminhorner** [Ramotion/animated-tab-bar#34]
I have tried setting the tintColor via UITabBar.appearance().tintColor = UIColor.greenColor() or even in the Interface Builder and to no avail. It doesn't seem to work

**Comment by MHX792** [comment]
Same here. Any solutions?

**Comment by ober01** [comment]
I added method  changeSelectedColor(textSelectedColor:UIColor, iconSelectedColor:UIColor)
