### ISSUE TITLE
Root View Controller seemingly lost upon tab switch while Modal View is active

### ISSUE THREAD

**Issue by Hsaylor** [Ramotion/animated-tab-bar#39]
I noticed that if I switch tabs while a modal window is up and then return to the tab, the controller behind the modal turns into a complete black screen. I imagine this is not intended behavior?

 I was able to implement a fix by closing the modal upon tab switch, which was fine for me, however it's not the most elegant fix as closing a modal upon moving away from it is not a behavior desired by everyone.

**Comment by ober01** [comment]
Can't reproduce 
![screen recording 2018-04-16 at 11 00 am](https://user-images.githubusercontent.com/5435782/38796902-84aadcae-4165-11e8-944f-99236ccbb27d.gif)
