### ISSUE TITLE
Urgently: How can I change the selectedIndex tab?

### ISSUE THREAD

**Issue by TareqElMasri** [Ramotion/animated-tab-bar#43]
When I use tabBarController?.selectedIndex it doesn't change the color in the animated tab, and I have tried using setSelectIndex() function but it didn't work, I really like this library but I have a deadline. Thanks in advance.

**Comment by cdf1982** [comment]
I have the same issue, have you figured out a solution?

**Comment by cdf1982** [comment]
It looks like I made it work, but I don't really like my own solution, so anyone more expert than me (meaning, everyone ;) is more than welcome to suggest a better way.

If you need to start your app in a different tab from the first one, it's pretty straightforward:

```swift
        let ramTBC = self.window!.rootViewController as! RAMAnimatedTabBarController

        ramTBC.selectedIndex = myDestination

        ramTBC.setSelectIndex(from: 0, to: myDestination)  // Because by default createCustomIcons() of RAMAnimatedTabBarController sets the selectedState for the item at index 0
```

If you need to switch programmatically from one tab to another during the execution of the app:

```swift
        let currentIndex : Int? = self.tabBarController?.selectedIndex

        self.tabBarController?.selectedIndex = myDestination
        
        if let ramTBC = self.tabBarController as? RAMAnimatedTabBarController,
           let current = currentIndex {

            ramTBC.setSelectIndex(from: current, to: myDestination)
        }
```

I hope it helps.

@cdf1982

**Comment by aalzanki** [comment]
I just added a new method called setSelectedTabToIndex to the RAMAnimatedTabBarController class

    func setSelectedTabToIndex(index: Int) {
        let items = tabBar.items as! [RAMAnimatedTabBarItem]
        
        let currentIndex = index
        if selectedIndex != currentIndex {
            let animationItem : RAMAnimatedTabBarItem = items[currentIndex]
            let icon = iconsView[currentIndex].icon
            let textLabel = iconsView[currentIndex].textLabel
            animationItem.playAnimation(icon, textLabel: textLabel)
            
            let deselelectIcon = iconsView[selectedIndex].icon
            let deselelectTextLabel = iconsView[selectedIndex].textLabel
            let deselectItem = items[selectedIndex]
            deselectItem.deselectAnimation(deselelectIcon, textLabel: deselelectTextLabel)
            
            selectedIndex = index
        }
    }

**Comment by TareqMasri** [comment]
@cdf1982 @aalzanki Thanks guys, that was helpful, I'll test it and I'll inform you

**Comment by randeepbhatia** [comment]
The func setSElectedTabToIndex raises null pointer exception

**Comment by cdf1982** [comment]
Have you tried my approach?

**Comment by TareqMasri** [comment]
@cdf1982 your soultion worked perfectly, thanks man

**Comment by sentiasa** [comment]
@cdf1982 Hey man. I tried to use your solution but I couldn't make it work. My cycle goes like LoginVC->TabBarCont->first Item opens up. I wanted to change that to the last one of four.

First, I tried adding your code inside viewDidLoad in RAMAnimatedTabBarController.swift (in pods). My currentIndex is returning nil.
```
        let currentIndex : Int? = self.tabBarController?.selectedIndex
        print(currentIndex)
        let myDest = 3
        self.tabBarController?.selectedIndex = myDest
        
        if let ramTBC = self.tabBarController as? RAMAnimatedTabBarController,
            let current = currentIndex {
                
                ramTBC.setSelectIndex(from: current, to: myDest)
        }
```

What should I exactly do? I'd be grateful if you answer me.

**Comment by sentiasa** [comment]
@cdf1982 Thanks man! I tried the AppDelegate part and your solution worked perfectly.

However, my icon is using BounceAnimation but for the initial part (the AppDelegate part), the icon gets initialised with some offset below.. Is there a way to push it back up manually in the AppDelegate (to achieve it with a workaround) because on the other times later in the app, it behaves as expected. It's just the AppDelegate part. What may be the problem? How can I overcome this do you think? Thanks

**Comment by sesur** [comment]
@cdf1982    I have found other way of implementation if you need to start your app in a different tab from the first one:
```  override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
         setSelectIndex(from: 0, to: 1)
    }  swift```

**Comment by sesur** [comment]
@cdf1982  I have found a other if you need to start your app in a different tab from the first one, use 

```override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
         setSelectIndex(from: 0, to: youDestination)  
    } ```

**Comment by sesur** [comment]
@cdf1982 I have found other way to set up you preferred tab when app starts, use: 
` 
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
         setSelectIndex(from: 0, to: 1)
    } 

`

**Comment by wei-go** [comment]
Based on @aalzanki solution,
I modified the function as easier below

**RAMAnimatedTabBarController.swift**
```
open func setSelectedTabToIndex(index: Int) {
        guard let items = tabBar.items as? [RAMAnimatedTabBarItem] else {
            fatalError("items must inherit RAMAnimatedTabBarItem")
        }
        let currentIndex = index
        if selectedIndex != currentIndex {
            let animationItem : RAMAnimatedTabBarItem = items[currentIndex]
            let animationItemSelected : RAMAnimatedTabBarItem = items[selectedIndex]
            animationItem.playAnimation()
            animationItemSelected.deselectAnimation()
            selectedIndex = index
        }
    }
```
**Usage**
If your TabBarController is addressed under app.window as rootViewController,
you can make a class function to control your TabBarController

**AppHelper.swift**
```
class AppHelper: NSObject {
class func selectTabBarIndexTo(index: Int) -> Void {
        if let app = UIApplication.shared.delegate as? AppDelegate, let window = app.window {
            (window.rootViewController as! RAMAnimatedTabBarController).setSelectedTabToIndex(index: index)
        }
    }
}
```
and call above function from the other ViewController class
```
AppHelper.selectTabBarIndexTo(index: 0) // To tabIndex
```

@aalzanki Thanks for your answer to solved my issue 👍
