### ISSUE TITLE
Animated tab bar is hidden however still tap gesture is active 

### ISSUE THREAD

**Issue by satyamub** [Ramotion/animated-tab-bar#44]
Hi,
I am trying to use this tab bar where I need to hide  the tab bar however I am unable to remove gesture recogniser. Would it be possible so that in a particular view controller, i would disable selecting tab items.

**Comment by akring** [comment]
Same problem,I used Reveal and found that there were two UIViews on the bottom of the VC,which alpha is 0 and can trigger gesture.

**Comment by satyamub** [comment]
There should be a code to hide the tab bar completely!!!

**Comment by akring** [comment]
Yep,I give it up and back to system tabBar again:(

**Comment by ober01** [comment]
use method func animationTabBarHidden(isHidden:Bool) to hidde tabbar

**Comment by satyamub** [comment]
@ober01 will there be no gesture on touch on those places after using this method?

**Comment by pxhkevin** [comment]
How to use function:  func animationTabBarHidden(isHidden:Bool) in project?

**Comment by sentiasa** [comment]
I also tried calling `tabBarController?.tabBar.hidden = true` in `viewDidLoad`, it works. However, it doesn't work if I call it in tapGesture. 

I also couldn't make it work with TabBarHidden function. `tabBarController!` or ``tabBarController!.tabBar` seems to have this function.
