### ISSUE TITLE
No shared scheme for Carthage

### ISSUE THREAD

**Issue by csjones** [Ramotion/animated-tab-bar#46]
I'd like to include this project in my cartfile but the RAMAnimatedTabBarDemo project file doesn't contain a shared xcode scheme thus `carthage update` fails. An embedded framework wouldn't be necessary that way iOS 7 can still be targeted. I'd submit a pull request but I'm not certain how the .gitignore should be updated to allow these changes to be included.

**Comment by 0x686169** [comment]
yes, please support Carthage !!!
