### ISSUE TITLE
Errors in Project-swift.h

### ISSUE THREAD

**Issue by jrgalan** [Ramotion/animated-tab-bar#49]
Having issues compiling in Xcode 7 beta 6 (Swift 2.0).

Getting a compile error:

```Type argument 'CGImageRef' (aka 'struct CGImage *') is neither an Objective-C object nor a block type```

Please see the attached screen.  This is in the autogenerated "Project-swift.h" file.

Any ideas how to fix this?  Kinda stuck here.

Thanks!

![ram_swift_errors](https://cloud.githubusercontent.com/assets/3075714/9620744/3966e722-50ba-11e5-8c65-d5eef6b14a88.png)

**Comment by jrgalan** [comment]
Filed a bug report for this with Apple based on a discussion thread:

https://forums.developer.apple.com/thread/16289

It seems Xcode 7 beta 6 is treating Array<CGImage> as a type that can be represented faithfully in Objective-C.  No bueno.

Workaround is is follows in RAMFrameItemAnimation:

    @nonobjc
    var animationImages : Array<CGImage> = Array()

and

    @nonobjc
    func playFrameAnimation(icon : UIImageView, images : Array<CGImage>) 

Hope that helps someone!

**Comment by tariq235** [comment]
Thanks for solution :+1:
