### ISSUE TITLE
Raised middle tab icon

### ISSUE THREAD

**Issue by benmaliel** [Ramotion/animated-tab-bar#53]
Have you included a custom class for the raised middle tab bar icon included in your first mockup GIF?

**Comment by nassarofficial** [comment]
I solved this issue by creating an "if condition" around
              
          createConstraints(icon, container: container, size: itemImage.size, yOffset: -5)

 in the RAMAnimatedTabBarController, and change the yOffset.

                if let itemImage = item.image {
                    if 2 == index { // selected first elemet
                    createConstraints(icon, container: container, size: itemImage.size, yOffset: 0)
                    } else {
                        createConstraints(icon, container: container, size: itemImage.size, yOffset: -5)

                    }
                }

**Comment by sentiasa** [comment]
@nassarofficial I couldn't get what you did exactly. Can you please explain it from the beginning? I installed the pods, set the storyboard (tabvc and views) and set the classes as shown in the read.me. The items are animating. However, my image insets (offsets) for bar items doesn't seem to work. As far as I understand, you put it in ViewDidLoad of the RAMAnimatedTabBarController. What exactly do I need to put, and where? Can you please guide me on that? I'd be grateful

[TabBarProblem.zip](https://github.com/Ramotion/animated-tab-bar/files/209569/TabBarProblem.zip)
