### ISSUE TITLE
RAMAnimatedTabBarController with Swift 2 and Pod

### ISSUE THREAD

**Issue by jorgecasariego** [Ramotion/animated-tab-bar#58]
I installed animated-tab-bar using Pod in this way

pod 'RAMAnimatedTabBarController', '~> 1.0'

but RAMAnimatedTabBarController.swift is not the same file that is here
https://github.com/Ramotion/animated-tab-bar/blob/master/RAMAnimatedTabBarController/RAMAnimatedTabBarController.swift

So, I'm having a lot of errors because the downloaded  file  is not Updated to Swift 2.0 syntax

What I'm doing wrong?

**Comment by efremidze** [comment]
Use the master branch
```
pod 'RAMAnimatedTabBarController', :git => 'https://github.com/Ramotion/animated-tab-bar.git'
```

**Comment by Gumarelo** [comment]
Thanks @efremidze

**Comment by hash3r** [comment]
There is an absence of the actual tag(1.0.2) in the repo
Workaround to get Swift2 compatible code:
```pod 'RAMAnimatedTabBarController', :git => 'https://github.com/Ramotion/animated-tab-bar.git', :commit => 'ed43b56'```
