### ISSUE TITLE
Pop to root view controller every time tab is clicked ?

### ISSUE THREAD

**Issue by shanmarkus** [Ramotion/animated-tab-bar#63]

**Comment by MHX792** [comment]
Came here to ask for this. +1

**Comment by MHX792** [comment]
From another issue I got the following code:

    func tapHandler(gesture:UIGestureRecognizer) {
        
        let items = tabBar.items as! [RAMAnimatedTabBarItem]
        
        let currentIndex = gesture.view!.tag
        let viewController = viewControllers![currentIndex]
        
        if let shouldSelect = delegate?.tabBarController?(self, shouldSelectViewController: viewController)
            where !shouldSelect {
            return
        }
        
        if selectedIndex != currentIndex {
            let animationItem : RAMAnimatedTabBarItem = items[currentIndex]
            let icon = iconsView[currentIndex].icon
            let textLabel = iconsView[currentIndex].textLabel
            animationItem.playAnimation(icon, textLabel: textLabel)
            
            let deselelectIcon = iconsView[selectedIndex].icon
            let deselelectTextLabel = iconsView[selectedIndex].textLabel
            let deselectItem = items[selectedIndex]
            deselectItem.deselectAnimation(deselelectIcon, textLabel: deselelectTextLabel)
            selectedIndex = gesture.view!.tag
            delegate?.tabBarController?(self, didSelectViewController: viewController)
        } else {
            let animationItem : RAMAnimatedTabBarItem = items[currentIndex]
            let icon = iconsView[currentIndex].icon
            let textLabel = iconsView[currentIndex].textLabel
            animationItem.playAnimation(icon, textLabel: textLabel)
            
            selectedIndex = gesture.view!.tag
            delegate?.tabBarController?(self, didSelectViewController: viewController)
            viewController.navigationController?.popToRootViewControllerAnimated(true)
            print("viewController: \(viewController)") 
            // prints same instance as in the viewDidLoad method of the navigation controller of selected tab
        }
    }

It successfully instantiates the navigation controller but unfortunately `popToRootViewControllerAnimated` doesn't work.

Anyone an idea how to fix this?

**Comment by ober01** [comment]
I don't understand the question, can you describe the problem more fully?
