### ISSUE TITLE
why cocoapods installs outdated version

### ISSUE THREAD

**Issue by muhasturk** [Ramotion/animated-tab-bar#64]
pod specs is outdated. How can we update this?

https://github.com/CocoaPods/Specs/blob/master/Specs/RAMAnimatedTabBarController/1.0.1/RAMAnimatedTabBarController.podspec.json

**Comment by maxhis** [comment]
+1
Really hate to copy/paste code into my project. For a solution, I set the git url and tag for  RAMAnimatedTabBarController:
`pod 'RAMAnimatedTabBarController', :git => 'https://github.com/Ramotion/animated-tab-bar.git', :tag => '1.0.5'`

**Comment by muhasturk** [comment]
Yes the solution you gave works well however cocoapods need upgrade to solve the problem.

**Comment by ober01** [comment]
fixed

**Comment by maxhis** [comment]
It is still installing the `1.0.1` version of library when run `pod install`.

**Comment by ober01** [comment]
run pod update

**Comment by maxhis** [comment]
Yeah, it works. Sorry for my mistake.
