### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) 

### ISSUE THREAD

**Issue by muhasturk** [Ramotion/animated-tab-bar#65]
![](http://s14.postimg.org/7p7t3q6bl/Screen_Shot_2015_12_10_at_03_33_09.png)

````
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 
```

**Comment by grahammccarthy** [comment]
@ober01  you closed this without providing any resolution. Can you leave a comment as to what causes this error?  Thanks!

**Comment by grahammccarthy** [comment]
If it at all helps, my specific issue was that I used the RAMFrameItemAnimation animation without specifying the imagesPath shown here:
![image](https://cloud.githubusercontent.com/assets/1336930/12635727/6e4aa55a-c554-11e5-9ee0-822afc2f6ef5.png)
