### ISSUE TITLE
Badge bug.

### ISSUE THREAD

**Issue by GuyKahlon** [Ramotion/animated-tab-bar#67]
When I set the tabbar badge to nil twice in a row the badge appears just red circle without text (number) instead of disappearing.

I fixed it by update the method:

    override var badgeValue: String? {
        get {
            return badge?.text
        }
        set(newValue) {
            
            if newValue == nil {
                badge?.removeFromSuperview()
                badge = nil;
                return
            }
            
            if badge == nil { // remove => && badge != nil
                badge = RAMBadge.bage()
                if let contanerView = self.iconView!.icon.superview {
                    badge!.addBadgeOnView(contanerView)
                }
            }
            
            badge?.text = newValue
        }
    }
 
Thanks

**Comment by ober01** [comment]
fixed, thanks.
