### ISSUE TITLE
please update cocoapod 

### ISSUE THREAD

**Issue by wupengnash** [Ramotion/animated-tab-bar#68]
here is the code
wupengdeAir:iOS-ArtCircle wupeng$ gem source -l 
*** CURRENT SOURCES ***

https://rubygems.org/
wupengdeAir:iOS-ArtCircle wupeng$ pod search RAMAnimatedTabBarController

-> RAMAnimatedTabBarController (1.0.1)
   RAMAnimatedTabBarController is a Swift module for adding animation to tabbar
   items.
   pod 'RAMAnimatedTabBarController', '~> 1.0.1'
   - Homepage: https://github.com/Ramotion/animated-tab-bar
   - Source:   https://github.com/Ramotion/animated-tab-bar.git
   - Versions: 1.0.1 [master repo]

**Comment by ober01** [comment]
pod search RAMAnimatedTabBarController


-> RAMAnimatedTabBarController (1.0.5)
   RAMAnimatedTabBarController is a Swift module for adding animation to tabbar
   items.
   pod 'RAMAnimatedTabBarController', '~> 1.0.5'
   - Homepage: https://github.com/Ramotion/animated-tab-bar
   - Source:   https://github.com/Ramotion/animated-tab-bar.git
   - Versions: 1.0.5, 1.0.1 [master repo]
admin@Alex-K ~>
