### ISSUE TITLE
Change tabTar image icon tintColor doesn't work.

### ISSUE THREAD

**Issue by GuyKahlon** [Ramotion/animated-tab-bar#69]
There isn't a way to change the tabbar image icon tint color.

I've tried the:
UITabBar.appearance()tintColor = UIColorredColor()

Thanks

**Comment by ober01** [comment]
RAMAnimatedTabBarItem have property  var iconView: (icon: UIImageView, textLabel: UILabel)?

your can try self.tabBarItem.itemView.icon.tintColor = UIColorredColor()

**Comment by GuyKahlon** [comment]
I have tried this, Unfortunately it dosen't work.

**Comment by mitchellporter** [comment]
I'm having the same problem as well.

**Comment by ober01** [comment]
in 1.0.6 version, added iconColor property
