### ISSUE TITLE
incorrect posizione on scale viewcontroller

### ISSUE THREAD

**Issue by AmeerTgh** [Ramotion/animated-tab-bar#71]
when i scale view controller and show modal view. tab bar items changed position
![img_7459](https://cloud.githubusercontent.com/assets/12966060/12088436/67d8743e-b2f0-11e5-9176-85757c8b4f61.PNG)

**Comment by ober01** [comment]
Now it's works 
<img width="442" alt="image 2018-04-16 at 11 13 30 am" src="https://user-images.githubusercontent.com/5435782/38797492-4d4b5944-4167-11e8-9798-6194483d4a36.png">
