### ISSUE TITLE
How to set UITabBarItem color

### ISSUE THREAD

**Issue by googlb** [Ramotion/animated-tab-bar#72]
I Set the class of the UITabBarController to RAMAnimatedTabBarController in your Storyboard 
How to set UITabBarItem color
I try this in AppDelegate
let mainColor = UIColor(rgba: "#45BDCF")
        UITabBar.appearance().tintColor = mainColor
        UITabBarItem.appearance().setTitleTextAttributes([NSForegroundColorAttributeName:mainColor], forState:.Normal)
it dosen't work.

**Comment by ober01** [comment]
in 1.0.6 version, added iconColor property

you need use textColor, iconColor property in RAMAnimatedTabBarItem
