### ISSUE TITLE
Possible to work with different images of selected and unselected state?

### ISSUE THREAD

**Issue by OptTrader** [Ramotion/animated-tab-bar#75]
Is it possible to work on the animation with 2 different images for each tab (selected & unselected)?

I'm assuming it doesn't work. Just want to check.

**Comment by ober01** [comment]
yes  you can, just add custom animation class. Look section "Creating Custom Animations" in README.md.
change image in this methods:

``` swift
override func playAnimation(icon : UIImageView, textLable : UILabel) {
    // add animation
   .....
   icon.image = selectedImage
   ....
  }
  // method call when Tab Bar Item is deselected
  override func deselectAnimation(icon : UIImageView, textLable : UILabel, defaultTextColor : UIColor) {
    // add animation
   .....
   icon.image = normalImage
   ....
  }
```

**Comment by savasadar** [comment]
I am going crazy,  How can I access "selectedImage" from in custom animation.

**Comment by lyc2345** [comment]
Hi, I have same question with @savasadar How can I access selectedImage in CustomAnimation class?

**Comment by lyc2345** [comment]
@savasadar I solved selectedImage by create a `img` and a `selectedImg` in a custom RAMAnimatedTabBarItem. Because the original `image` and `selectedImage` somehow effect each other.

```
class HostAnimatedTabBarItem: RAMAnimatedTabBarItem {
  var img: UIImage?
  var selectedImg: UIImage?
}
```

Then also create a weak item: RAMAnimatedTabBarItem in a overrided RAMItemAnimation class.

```
class HostBounceAnimation: RAMItemAnimation {

  weak var tabBarItem: RAMAnimatedTabBarItem?
}
```

```
let item = HostAnimatedTabBarItem(title: ..., image: ..., selectedImage: ...)
let animation = HostBounceAnimation()
item.animation = animation
animation.tabBarItem = item
```

Final step is assigning your item with your new img or selectedImg property.

```
  override func playAnimation(_ icon: UIImageView, textLabel: UILabel) {
    playBounceAnimation(icon)
    textLabel.textColor = Configuration.Theme.darkBlue
    guard let item = tabBarItem as? HostAnimatedTabBarItem else {
      fatalError("item selected image is nil")
    }
    icon.image = item.selectedImg
  }
```
Do the same thing with your deselect method. I think it will work like a charm.
