### ISSUE TITLE
Change selected and unselected icon colors?

### ISSUE THREAD

**Issue by fedesenmartin** [Ramotion/animated-tab-bar#76]
How do I Change the selected and deselect color in for example bounce animation?
thx

**Comment by ober01** [comment]
RAMAnimatedTabBarItem have properties :  (normal state)
  ``` swift
    @IBInspectable var textColor: UIColor
    @IBInspectable var iconColor: UIColor
  ``` 

RAMItemAnimation have properties : (selected state)
``` swift
    @IBInspectable var textSelectedColor: UIColor
    @IBInspectable var iconSelectedColor: UIColor!
  ``` 

you can change in Attributes inspector in Storyboard

**Comment by fedesenmartin** [comment]
Thanks!

**Comment by joaohkfaria** [comment]
This works on Swift? I tried to apply this attributes and it didn't work...

**Comment by joaohkfaria** [comment]
Ok, it's working withchangeSelectedColor function, sorry to bother :)

**Comment by kiwo12345** [comment]
@ober01 I can only see textColor/iconColor and Bg defaul/Bg selected, not textSelectedColor or iconSelectedColor in the Attributes inspector
