### ISSUE TITLE
Support for non-storyboard UI's

### ISSUE THREAD

**Issue by jlaws** [Ramotion/animated-tab-bar#77]
- [ ] RAMAnimatedTabBarItem needs to have the animation, textColor, and iconColor properties set to public.
- [ ] RAMItemAnimation and its subclasses need to be made public
- [ ] RAMFrameItemAnimation, RAMTransitionItemAnimations and RAMRotationAnimation need to have public properties
- [ ] RAMTransitionItemAniamtions and its subclasses are misspelled and should be fixed.

**Comment by ober01** [comment]
thanks
