### ISSUE TITLE
Push to a Navigation Controller

### ISSUE THREAD

**Issue by nlogioco** [Ramotion/animated-tab-bar#82]
Issue 1: **Pushing to a new view from tab bar controller**
When you do this, the tab bar icons stay on the screen when they should have disappeared during the transition animation. (The icons are now overtop of a view that should be on top of the icons)

Issue2: **Popping the view you just pushed to go back to the tab bar controller**
When you do this, it seems like the original tab bar is now covering the tab bar icons we added originally.

I haven't come up with a solution, but will be looking for one and will post a solution if I find one.

**Comment by ober01** [comment]
you can use this method ``` public func animationTabBarHidden(isHidden:Bool) ``` to hide tab bar

**Comment by nlogioco** [comment]
I found where the problem happens.
`    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if segue.identifier == "ToVC2" {
            if let destVC = segue.destinationViewController as? VC2 {
                destVC.hidesBottomBarWhenPushed = true
            }
        }
    }`

The problem is `destVC.hidesBottomBarWhenPushed = true`

This causes the tab bar to disappear, but our custom tab bar icons we made (uiimageview/uiview) stay on the screen.
