### ISSUE TITLE
add hidesBottomBarWhenPushed support or hide/show animation

### ISSUE THREAD

**Issue by AliThink** [Ramotion/animated-tab-bar#84]
suggest add hidesBottomBarWhenPushed support or hide/show animation
thx.

**Comment by ducky007** [comment]
There is already support to hide the bar. Use something like the following in your code...

  let animatedTabBar = self.tabBarController as! RAMAnimatedTabBarController
  animatedTabBar.animationTabBarHidden(true)

**Comment by AliThink** [comment]
thx for reply .I know this method.But it's no animation when hide or show. Add some animation will better.

**Comment by WangHengHeng** [comment]
regrettable

**Comment by Geeerry** [comment]
THX

**Comment by eggswift** [comment]
@AliThink Try this https://github.com/eggswift/ESTabBarController, supported hidesBottomBarWhenPushed.
