### ISSUE TITLE
Cant change font of tab bar

### ISSUE THREAD

**Issue by kiwo12345** [Ramotion/animated-tab-bar#98]
I am trying to change the font by using this in AppDelegate

```
let appearance = UITabBarItem.appearance()
let attributes = [NSFontAttributeName:UIFont(name: "AvenirNext-Regular", size: 10)!]
appearance.setTitleTextAttributes(attributes, forState: .Normal)
```

But nothing happens.

Is there any other way to change the tab fonts?

**Comment by ober01** [comment]
for case let item as RAMAnimatedTabBarItem in tabBarController?.tabBar.items {
        item.iconView?.textLabel.font = newFont
}

**Comment by kiwo12345** [comment]
@ober01 thanks. Where should I put this code?

**Comment by ober01** [comment]
you can subclass from RAMAnimatedTabBarItem and add this code in viewDidLoad

**Comment by hmalc** [comment]
For Swift 3

```
override func viewDidLoad() {
super.viewDidLoad()
        for case let item as RAMAnimatedTabBarItem in self.tabBar.items! {
              item.iconView?.textLabel.font = UIFont.exampleAvenirLight(ofSize: 10)
        }
    }
```
