### ISSUE TITLE
How to change iconSelectedColor with RAMBounceAnimation

### ISSUE THREAD

**Issue by Geeerry** [Ramotion/animated-tab-bar#99]
At first thx your guys created such great project.
but when i use the RAMBounceAnimation I don't know how to change the iconSelectedColor..
Thx.

**Comment by ober01** [comment]
RAMBounceAnimation have public property 
@IBInspectable public var iconSelectedColor: UIColor!

**Comment by Geeerry** [comment]
Yeah
I found this but I don't know how to change this property and where to add the code...😔

**Comment by ober01** [comment]
Are you use storyboards ?

**Comment by Geeerry** [comment]
yeah
I am just start learning iOS programming...
Thx.

**Comment by ober01** [comment]
read this post https://www.weheartswift.com/make-awesome-ui-components-ios-8-using-swift-xcode-6/

**Comment by Geeerry** [comment]
Thanks😊☺️
I have solved this issue.
